### ISSUE TITLE
Android端，无法进行插件调试

### ISSUE THREAD

**Issue by EthanJMY** [MiEcosystem/NewXmPluginSDK#10]
每次调试，都提示插件签名错误，首先想到，可能是开发者平台中，签名配置的原因，但去开发者平台中寻找，并未找到签名配置的地方，想要重新开启一个新项目，但审核了五天了，还没有审核通过，希望有大佬来给我指条明路

**Comment by wangchongwhut** [comment]
签名md5信息详细提交方式：
1）使用上述申请DevelopId的账号登录小米IoT开放平台
2）点击右上角个人信息页面，打开个人开发者页面
3）在个人开发者页面的“扩展程序公钥”框输入上述md5信息
