### ISSUE TITLE
无法获取设置中语言列表

### ISSUE THREAD

**Issue by Alanqiu** [MiEcosystem/NewXmPluginSDK#100]
我想通过api获取到 APP中 我的-设置-语言 下面的语言列表 和当前设置的语言。但是查看api 文档未发现类似的api。可以帮忙提供类似的api 吗？谢谢

**Comment by zanetti4** [comment]
请问您是哪个公司的开发者？这是什么产品？另外，我们这边对于旧版插件的 api 不再进行维护了，请知悉。

**Comment by Alanqiu** [comment]
飞米的小相机，相机类的因为用到解码库。新插件不支持，所以一直使用旧版的。
