### ISSUE TITLE
通用设置界面，网络信息栏目，不同账号，不同设备，有的会显示有的没有显示

### ISSUE THREAD

**Issue by uuuust1111** [MiEcosystem/NewXmPluginSDK#102]
#### 环境
插件 model  ： com.midr.rvmirror.m5
使用的哪个方法  ：  openMoreMenu2
请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象
通用设置界面，网络信息栏目，不同账号，不同设备，有的会显示有的没有显示

#### 期望

希望知道能控制网络信息栏目的api

**Comment by zanetti4** [comment]
这个问题涉及到什么手机系统？显示和不显示网络信息栏目的设备分别是哪些？
