### ISSUE TITLE
离线状态进入插件后，如果设备上线了，是否可以拿到最新状态

### ISSUE THREAD

**Issue by sunhongda** [MiEcosystem/NewXmPluginSDK#103]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
插件 model 是什么
使用的哪个方法
请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象

请使用 logcat 导出所有进程的 log
简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by zanetti4** [comment]
请问涉及到的设备是什么？手机系统是什么？
