### ISSUE TITLE
米家App - 保存默认灯光功能在局域网模式下不正确

### ISSUE THREAD

**Issue by andysun-yeelight** [MiEcosystem/NewXmPluginSDK#104]
米家版本: 5.5.25
OS: Android
Model: yeelink.light.color1 （其他有此功能的灯，功能也不正确，如yeelink.light.strip1, yeelink.light.strip2等）
UID: 1858826010
DID: 86938038

测试场景:
1. 远程连接模式
1） 打开米家App -> 打开彩光灯泡插件 (yeelink.light.color1 )
2） 关灯
3） 打开设置/设备设置/默认状态 -> 点击保存默认灯光
4)  结果 -> 保存失败 (这是正确的行为)

2. 局域网模式
1） 打开米家App -> 打开彩光灯泡插件 (yeelink.light.color1 )
2） 关灯
3） 打开设置/设备设置/默认状态 -> 点击保存默认灯光
4)  结果 -> 保存成功 (这是错误的行为)

SDK接口，参数一会儿让开发人员更新。

**Comment by andysun-yeelight** [comment]
![101560318995_ pic](https://user-images.githubusercontent.com/51732093/59326836-58344f00-8d1a-11e9-9d6f-6595cb85bfcd.jpg)
![121560319037_ pic](https://user-images.githubusercontent.com/51732093/59326854-68e4c500-8d1a-11e9-8bad-3f351fd1488b.jpg)
附件里是调用的API, callMethod是米家API, set_default是我们固件方法。
从plugin里的日志看，当在局域网时，plugin能收到set_default方法的回复，但是当在远程模式时，收不到云端的回复。

**Comment by lvjie0519** [comment]
@andysun-yeelight 
从plugin里的日志看，当在局域网时，plugin能收到set_default方法的回复，但是当在远程模式时，收不到云端的回复。

---------------------------------------
1、你的意思是 在远程模式下，需要收到云端的回复是吗？
2、在调用 callMethod 方法的时候， 选择core进程，看下logcat里面输出的log日志呢？访问云端会发起rpc网络请求。
