### ISSUE TITLE
米家APP插件

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/NewXmPluginSDK#105]
如何在通用设置里面自定义并且添加“修改设备名称”和“解除链接”，请问如何这个接口怎样调用？

**Comment by blockdate** [comment]
`Host.ui.openChangeDeviceName()`

`Host.ui.openDeleteDevice(title = null)`

**Comment by Aphrodite123** [comment]
没有这个，这是新版RN用的吗？现在的问题还是老版插件里头的




------------------ 原始邮件 ------------------
发件人: "wulei"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 上午10:26
收件人: "MiEcosystem/NewXmPluginSDK"<NewXmPluginSDK@noreply.github.com>;
抄送: "Aphrodite"<927467936@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MiEcosystem/NewXmPluginSDK] 米家APP插件 (#105)




Host.ui.openChangeDeviceName()
 
Host.ui.openDeleteDevice(title = null)
