### ISSUE TITLE
米家调试APK测试账号无法登录，需要安全验证

### ISSUE THREAD

**Issue by sky1226** [MiEcosystem/NewXmPluginSDK#106]
- 米家调试APK下载地址：http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_apk_5ac6e5d37cc13085a6b4b30f66a18113.apk
- 登录测试账号：用户名:923522198, 密码:123asdzxc 
- 现象：账号密码登录后跳转到 “小米账号安全验证页面”。参见下图：
![tempFileForShare_2019-06-11-18-00-28](https://user-images.githubusercontent.com/15668203/59500305-c1a78f80-8ecb-11e9-8ab1-0edda2760b04.jpg)

**Comment by zanetti4** [comment]
这是哪个手机系统？现在使用最新的米家 app，还有此问题吗？
