### ISSUE TITLE
菜单中，“检查固件更新”的小红点不正常的出现

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/NewXmPluginSDK#107]
设备：锁类设备，蓝牙BLE设备
手机操作系统： Android， 米家App 5.5.30
现象：进入插件，手机蓝牙未能连接到锁的情况下，调用接口，显示菜单。在“检查固件更新”这个菜单项上，直接显示了一个小红点（表示有固件可进行更新）。

问题： 由于蓝牙尚未连接，不可能获得到锁的现有固件版本。为什么在“检查固件更新”上会显示小红点。
只有Android会出现此情况，iPhone不会出现。

**Comment by wangchongwhut** [comment]
打开设置菜单时候，会让插件传入一个IBleUpgradeController对象，然后app会比较这个对象里面的getCurrentVersion()和getLatestVersion()，如果getLatestVersion()是新版本就显示小红点。你检查下这个对象的实现。
