### ISSUE TITLE
固件上报设备在线

### ISSUE THREAD

**Issue by Kevin-zhongyx** [MiEcosystem/NewXmPluginSDK#109]
Hello ,现在我们设备端绑定成功之后不知道怎么告诉APP设备在线。
![image](https://user-images.githubusercontent.com/53296204/61862147-f7468c00-aeff-11e9-9e78-bf29ac8bcd5b.png)
在APP上刷新的时候设备的log会一直打印
 mobile msg:{"id":1788,"method":"get_online","params":[]}
我查找了文档无法找到get_online这个方法 不知道如何回复。
---
"hw_ver":"Linux"
"fw_ver":"5.5.43_0721"
"model":"ydhome.cateye.pr1"

**Comment by zanetti4** [comment]
设备应该和后台通信，后台存储着设备的状态，app 向后台发送请求，获取设备状态。
