### ISSUE TITLE
继承XmPluginBaseActivity之后，setTheme会出错

### ISSUE THREAD

**Issue by Chgocn** [MiEcosystem/NewXmPluginSDK#11]
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTheme(R.style.Theme_Transparent);
        setContentView(R.layout.xxx);
    }
另AndroidAanifest.xml 为activity 设置theme属性无效。
希望有人能回答一下。

**Comment by wangchongwhut** [comment]
米家扩展程序里不支持配置theme，而且我们是通过接口代理的方式加载米家扩展程序的，不会读取AndroidManifest里面Activity配置信息。

**Comment by evansherry** [comment]
@wangchongwhut 插件不需要设置style吗？ 在style里面无法引用到lib里面的support包
