### ISSUE TITLE
设备固件跟APP插件交互协议

### ISSUE THREAD

**Issue by Kevin-zhongyx** [MiEcosystem/NewXmPluginSDK#110]
Hello ，大家好。
        现在设备固件已经成功绑定，p2p也login成功了 。APP也能看到设备，但是APP那边就是没法建立连接。不能发起p2p连线。请问一下有没有文档说明目前APP插件跟设备交互的流程跟协议。现在看起来我们的项目就卡在了跟APP交互这里，开发包里面是没有关于这方面的文档。
————————
"hw_ver":"Linux"
"fw_ver":"5.5.43_0721"
"model":"ydhome.cateye.pr1"

**Comment by zanetti4** [comment]
请问这个问题涉及到什么手机系统？
