### ISSUE TITLE
BleMeshDemo

### ISSUE THREAD

**Issue by fergus825** [MiEcosystem/NewXmPluginSDK#111]
#### 环境
插件 model 是什么：chuangmi.switch.mesh
用的哪个方法：XmPluginHostApi.instance().getPropertyValues()
 XmPluginHostApi.instance().setPropertyValue()

#### 现象
连接开关正常，点击获取灯的开关状态按钮弹出”获取开关状态失败“，查看log api回调结果中的resultCode为-704090001。

#### 期望
可以正常获得开关的状态

#### 其他的上下文/日志/截图
疑问如下：
- API文档中找不到getPropertyValues这个接口；

- 返回值-704090001代表何种错误未知；

- demo中的LIGHT_SERVICE_IID和SWITCH_STATUS_PROPERTY_IID均为定值，是否需要根据设备不同需要获取对应的值或者是需要在后台配置？

- 运行本demo目的是通过插件来控制mesh开关的开启和关闭，但是无效，是否是因为我们不需要LIGHT_SERVICE_IID？

**Comment by zanetti4** [comment]
请问此问题涉及到安卓还是 ios 系统？

**Comment by fergus825** [comment]
问题已经找到：是因为作为mesh网关使用的yeelight语音助手没有升级到最新测试版的原因，同时服务器环境还需切换到preview。
