### ISSUE TITLE
低功项目OTA无法唤醒设备

### ISSUE THREAD

**Issue by FlyerChao** [MiEcosystem/NewXmPluginSDK#112]
---

#### 环境
插件 model 是什么
----
chuangmi.cateye.ipc018

使用的哪个方法
----
点击 通用设置--固件升级

请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象

低功耗项目，在设备休眠的时候，点击固件升级按钮，未能唤醒设备，无法执行升级操作。

#### 期望

点击升级界面的时候能够唤醒系统，执行升级操作

#### 尝试过的解决办法
尝试过哪些操作？
----
升级界面无法控制，无法做出操作

**Comment by zanetti4** [comment]
已安排相关同事查看，请耐心等待。

**Comment by 18792576258** [comment]
ios是device.isOnline。Android插件中在线离线的解析是看不到的，所以无法推断设备到底应该传什么状态值。 
这个问题应该是设备没返回状态值。
设备会收到手机发来的获取状态的一些方法，但是这些方法收到之后不知道要怎么回复。get_online wakeup等（issue 109）
1. 设备端收到get_online wakeup这些状态值时需要回复的内容和格式是什么
2.为什么ios和Android判断设备在线离线的方法不一样

**Comment by gotone** [comment]
休眠设备不支持休眠的时候ota，因为都没上电。需要现保证设备处于正常工作状态，能够收到服务器下发的升级命令。
