### ISSUE TITLE
弹出Toast偶现崩溃

### ISSUE THREAD

**Issue by bairubing007** [MiEcosystem/NewXmPluginSDK#115]
home:plugin0 W/ResourceType: For resource 0x7f0c0194, entry index(404) is beyond type entryCount(39)
08-16 14:01:06.967 22900-22900/com.xiaomi.smarthome:plugin0 W/ResourceType: Failure getting entry for 0x7f0c0194 (t=11 e=404) (error -75)
08-16 14:01:06.968 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err: android.content.res.Resources$NotFoundException: String resource ID #0x7f0c0194
08-16 14:01:06.976 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getText(Resources.java:350)
08-16 14:01:06.977 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getString(Resources.java:444)
08-16 14:01:06.977 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.ToastInjector.addAppName(ToastInjector.java:49)
08-16 14:01:06.977 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:284)
08-16 14:01:06.978 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:267)
08-16 14:01:06.978 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.util.ToastUtil.showMessage(ToastUtil.java:101)
08-16 14:01:06.978 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.showToast(BaseActivity.java:452)
08-16 14:01:06.979 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.settingOk(BaseActivity.java:394)
08-16 14:01:06.979 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.access$200(BaseActivity.java:61)
08-16 14:01:06.979 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity$6.onSuccess(BaseActivity.java:319)
08-16 14:01:06.979 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity$6.onSuccess(BaseActivity.java:316)
08-16 14:01:06.979 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.xiaomi.smarthome.frame.plugin.host.PluginHostApi$5.run(PluginHostApi.java:322)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.handleCallback(Handler.java:793)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Looper.loop(Looper.java:173)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6698)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-16 14:01:06.980 22900-22900/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
08-16 14:01:07.001 22900-22900/com.xiaomi.smarthome:plugin0 I/Toast: Show toast from OpPackageName:com.xiaomi.smarthome, PackageName:com.xiaomi.smarthome

**Comment by bairubing007** [comment]
ResourceType: For resource 0x7f0c0194, entry index(404) is beyond type entryCount(39)
08-16 14:54:34.043 15254-15254/com.xiaomi.smarthome:plugin0 W/ResourceType: Failure getting entry for 0x7f0c0194 (t=11 e=404) (error -75)
08-16 14:54:34.043 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err: android.content.res.Resources$NotFoundException: String resource ID #0x7f0c0194
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getText(Resources.java:350)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getString(Resources.java:444)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.ToastInjector.addAppName(ToastInjector.java:49)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:284)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:267)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.util.ToastUtil.showMessage(ToastUtil.java:101)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.showToast(BaseActivity.java:452)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.settingOk(BaseActivity.java:394)
08-16 14:54:34.044 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity.access$200(BaseActivity.java:61)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity$6.onSuccess(BaseActivity.java:319)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.activity.base.BaseActivity$6.onSuccess(BaseActivity.java:316)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.xiaomi.smarthome.frame.plugin.host.PluginHostApi$5.run(PluginHostApi.java:322)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.handleCallback(Handler.java:793)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Looper.loop(Looper.java:173)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6698)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-16 14:54:34.045 15254-15254/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
08-16 14:54:34.057 15254-16603/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-1689-28-
08-16 14:54:34.057 15254-16603/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-16 14:54:34.067 15254-15254/com.xiaomi.smarthome:plugin0 I/Toast: Show toast from OpPackageName:com.xiaomi.smarthome, PackageName:com.xiaomi.smarthome
08-16 14:54:34.126 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: Failed to init thread tls key.
08-16 14:54:34.126 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: RsdCpuReference::create for driver hal failed.
08-16 14:54:34.126 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: Hal init failed,  libRSDriver.so
08-16 14:54:34.127 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: Failed to load default runtime!
08-16 14:54:34.127 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: Errors during thread init (sync mode)
08-16 14:54:34.127 15254-16217/com.xiaomi.smarthome:plugin0 E/RenderScript: rsAssert failed: mExit, in frameworks/rs/rsContext.cpp at 566
08-16 14:54:34.127 15254-16691/com.xiaomi.smarthome:plugin0 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb74 in tid 16691 (RenderThread)

**Comment by bairubing007** [comment]
08-18 15:52:08.035 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4641-28-
08-18 15:52:08.035 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.082 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-3414-28-
08-18 15:52:08.082 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.133 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4580-28-
08-18 15:52:08.133 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.174 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-3954-28-
08-18 15:52:08.174 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.200 932-3342/? I/NuPlayerDecoder: [audio] saw output EOS
08-18 15:52:08.201 932-3341/? D/AudioTrack: stop() called with 99397 frames delivered
08-18 15:52:08.201 917-4286/? E/AudioFlinger: open /proc/932/cmdline error
08-18 15:52:08.201 917-4286/? I/AudioFlinger: setAppName(), name=[], active=[0]
08-18 15:52:08.201 531-2341/? V/EffectDiracSound: DiracSound_command() start, cmdCode=23
08-18 15:52:08.201 531-2341/? V/EffectDiracSound: DiracSound_Command EFFECT_CMD_SET_APP_NAME: stream=5, name=-
08-18 15:52:08.236 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5031-28-
08-18 15:52:08.236 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.267 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-3918-28-
08-18 15:52:08.267 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.323 896-1079/? I/ThermalEngine: handle_thresh_sig: SS Id SKIN-SS-GOLD-AND-SILVER, Read xo_therm_buf 43000mC
08-18 15:52:08.369 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-6027-28-
08-18 15:52:08.369 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.431 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4902-28-
08-18 15:52:08.431 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.452 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-6656-28-
08-18 15:52:08.452 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.463 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5326-28-
08-18 15:52:08.463 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.534 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-6610-28-
08-18 15:52:08.535 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.565 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4130-28-
08-18 15:52:08.566 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.627 32573-32679/com.xiaomi.smarthome:core D/BootRequestCheck: 1566114728626 SmartHomeRc4Api.sendRequest Request{method=POST, url=https://api.io.mi.com/app/device/batchdevicedatas, tag=lZb70sHSs6g52p13/WjkGw==} com.xiaomi.smarthome:core
08-18 15:52:08.638 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5894-28-
08-18 15:52:08.638 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.668 932-3338/? D/NuPlayerDriver: notifyListener_l(0xece99cb0), (2, 0, 0, -1), loop setting(0, 0)
08-18 15:52:08.669 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4202-28-
08-18 15:52:08.670 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.670 1342-10828/? I/MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 1000/1898 clientId=android.media.AudioManager@e10aa12
08-18 15:52:08.671 1866-2361/? D/Avrcp: AudioManager Player: ID:12423 -- type:android.media.SoundPool -- u/pid:10516/32540 -- state:idle -- attr:AudioAttributes: usage=13 content=4 flags=0x0 tags= bundle=null
08-18 15:52:08.671 1866-2361/? D/Avrcp: AudioManager Player: ID:12487 -- type:android.media.AudioTrack -- u/pid:10516/2432 -- state:started -- attr:AudioAttributes: usage=1 content=2 flags=0x0 tags= bundle=null
08-18 15:52:08.672 1866-2361/? D/Avrcp: AudioManager isPlaying: true, mA2dpState: 11, isMusiActive: false
08-18 15:52:08.675 32573-1327/com.xiaomi.smarthome:core D/MIIO: host:api.io.mi.com prefix:nullpath:/device/batchdevicedatas method:POST params:[data:[{"did":"292198389","props":["prop.is_can_open_video"]}]]
08-18 15:52:08.675 32573-1327/com.xiaomi.smarthome:core D/MIIO: {"code":0,"message":"ok","result":{"292198389":{"prop.is_can_open_video":"\"1\""}}}
08-18 15:52:08.678 2432-2432/com.xiaomi.smarthome:plugin0 D/EquipmentProperty: voiceAlarm:  start alarm 3
08-18 15:52:08.731 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5485-28-
08-18 15:52:08.731 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.772 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4981-28-
08-18 15:52:08.772 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.783 2432-2432/com.xiaomi.smarthome:plugin0 W/ResourceType: For resource 0x7f0c0194, entry index(404) is beyond type entryCount(39)
08-18 15:52:08.783 2432-2432/com.xiaomi.smarthome:plugin0 W/ResourceType: Failure getting entry for 0x7f0c0194 (t=11 e=404) (error -75)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err: android.content.res.Resources$NotFoundException: String resource ID #0x7f0c0194
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getText(Resources.java:350)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.content.res.Resources.getString(Resources.java:444)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.ToastInjector.addAppName(ToastInjector.java:49)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:284)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.widget.Toast.makeText(Toast.java:267)
08-18 15:52:08.784 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.util.ToastUtil.showMessage(ToastUtil.java:93)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at com.meetvr.doorbell.android.view.PreviewVideoControl.onClick(PreviewVideoControl.java:625)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.view.View.performClick(View.java:6266)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.view.View$PerformClick.run(View.java:24730)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.handleCallback(Handler.java:793)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.os.Looper.loop(Looper.java:173)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6698)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-18 15:52:08.785 2432-2432/com.xiaomi.smarthome:plugin0 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
08-18 15:52:08.799 2432-2432/com.xiaomi.smarthome:plugin0 I/SETTING_PUSH_TAG: push json ( {"292198389":{"uid":"14009822","did":"292198389","time":1566114728798,"type":"prop","key":"remote_alert","value":"1"}} )
08-18 15:52:08.809 32573-32679/com.xiaomi.smarthome:core I/RPC: rpc is from cloud...
08-18 15:52:08.812 603-603/? D/SurfaceFlinger: duplicate layer name: changing com.xiaomi.smarthome/com.xiaomi.smarthome.frame.plugin.runtime.activity.PluginHostActivity to com.xiaomi.smarthome/com.xiaomi.smarthome.frame.plugin.runtime.activity.PluginHostActivity#1
08-18 15:52:08.828 32573-32679/com.xiaomi.smarthome:core D/BootRequestCheck: 1566114728814 SmartHomeRc4Api.sendRequest Request{method=POST, url=https://api.io.mi.com/app/home/rpc/292198389, tag=lZb70sHSs6g52p13/WjkGw==} com.xiaomi.smarthome:core
08-18 15:52:08.830 896-1079/? I/ThermalEngine: handle_thresh_sig: SS Id SKIN-SS-GOLD-AND-SILVER, Read xo_therm_buf 43000mC
08-18 15:52:08.834 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5485-28-
08-18 15:52:08.834 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.842 2432-2432/com.xiaomi.smarthome:plugin0 I/Toast: Show toast from OpPackageName:com.xiaomi.smarthome, PackageName:com.xiaomi.smarthome
08-18 15:52:08.875 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-4029-28-
08-18 15:52:08.876 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:08.942 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: Failed to init thread tls key.
08-18 15:52:08.942 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: RsdCpuReference::create for driver hal failed.
08-18 15:52:08.942 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: Hal init failed,  libRSDriver.so
08-18 15:52:08.943 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: Failed to load default runtime!
08-18 15:52:08.943 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: Errors during thread init (sync mode)
08-18 15:52:08.943 2432-2554/com.xiaomi.smarthome:plugin0 E/RenderScript: rsAssert failed: mExit, in frameworks/rs/rsContext.cpp at 566
08-18 15:52:08.944 2432-3366/com.xiaomi.smarthome:plugin0 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb74 in tid 3366 (RenderThread)
08-18 15:52:08.948 32573-769/com.xiaomi.smarthome:core D/MIIO: host:api.io.mi.com prefix:nullpath:/home/rpc/292198389 method:POST params:[data:{"id":8375,"method":"set_props","params":{"292198389":{"uid":"14009822","did":"292198389","time":1566114728798,"type":"prop","key":"remote_alert","value":"1"}}}]
08-18 15:52:08.948 32573-769/com.xiaomi.smarthome:core D/MIIO: {"code":0,"id":8375,"result":["ok"]}
08-18 15:52:08.967 32573-2561/com.xiaomi.smarthome:core D/ServerCompact: get server from cache: ServerBean: CN : cn 
08-18 15:52:08.969 32573-2561/com.xiaomi.smarthome:core I/STAT-REPORT: {type:result,key:zdy.fj3.gi2.0k3,value:
                                                                       {time:159,errorcode:0,model:mxiang.cateye.mdb10,did:292198389,extra:,key_name:rpc_remote_result,session:1566114654737,order:3},extra:,am:mihome,
                                                                       uid:14009822,time:1566114728}
08-18 15:52:08.972 32573-32691/com.xiaomi.smarthome:core I/STAT-SERVICE: {"type":"result","key":"zdy.fj3.gi2.0k3","value":"{\"time\":159,\"errorcode\":0,\"model\":\"mxiang.cateye.mdb10\",\"did\":\"292198389\",\"extra\":\"\",\"key_name\":\"rpc_remote_result\",\"session\":1566114654737,\"order\":3}","extra":"","am":"mihome","uid":"14009822","time":1566114728}
08-18 15:52:08.974 32573-32691/com.xiaomi.smarthome:core D/ServerCompact: get server from cache: ServerBean: CN : cn 
08-18 15:52:08.983 32573-32691/com.xiaomi.smarthome:core I/STAT-UPLOAD: {"ver":"v3","cid":"2859600533BEC6662F72A1D2FF8A9B2B530592C4","msid":"436B6570069D07C5C9C226E6CA4F2FCD55D5E80","mc":"ec:41:18:94:9e:06","av":"5.5.53","ov":"Android-8.0.0-V10.2.1.0.OAHCNFK","md":"MIX|{\"manu\":\"Xiaomi\",\"hard\":\"qcom\"}","am":"com.xiaomi.mihome","ch":"DEV","rd":[{"type":"result","key":"zdy.fj3.gi2.0k3","value":"{\"time\":159,\"errorcode\":0,\"model\":\"mxiang.cateye.mdb10\",\"did\":\"292198389\",\"extra\":\"\",\"key_name\":\"rpc_remote_result\",\"session\":1566114654737,\"order\":3}","extra":"","am":"mihome","uid":"14009822","time":1566114728}]}
08-18 15:52:08.994 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: false-false-5951-28-
08-18 15:52:08.994 2432-2628/com.xiaomi.smarthome:plugin0 D/MISS_CameraPlayer: onVideoData: 9999999999999true--false--0
08-18 15:52:09.008 3369-3369/? W/crash_dump32: type=1400 audit(0.0:6352): avc: denied { search } for name="com.xiaomi.smarthome" dev="dm-1" ino=2031775 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
08-18 15:52:09.008 3369-3369/? I/chatty: uid=10516(u0_a516) crash_dump32 identical 2 lines
08-18 15:52:09.018 3369-3369/? W/crash_dump32: type=1400 audit(0.0:6355): avc: denied { search } for name="com.xiaomi.smarthome" dev="dm-1" ino=2031775 scontext=u:r:crash_dump:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
08-18 15:52:09.023 32573-1622/com.xiaomi.smarthome:core E/MIIO: prefix:nullpath:/stat/stat_info method:POST params:[data:{"ver":"v3","cid":"2859600533BEC6662F72A1D2FF8A9B2B530592C4","msid":"436B6570069D07C5C9C226E6CA4F2FCD55D5E80","mc":"ec:41:18:94:9e:06","av":"5.5.53","ov":"Android-8.0.0-V10.2.1.0.OAHCNFK","md":"MIX|{\"manu\":\"Xiaomi\",\"hard\":\"qcom\"}","am":"com.xiaomi.mihome","ch":"DEV","rd":[{"type":"result","key":"zdy.fj3.gi2.0k3","value":"{\"time\":159,\"errorcode\":0,\"model\":\"mxiang.cateye.mdb10\",\"did\":\"292198389\",\"extra\":\"\",\"key_name\":\"rpc_remote_result\",\"session\":1566114654737,\"order\":3}","extra":"","am":"mihome","uid":"14009822","time":1566114728}]}]
08-18 15:52:09.023 32573-1622/com.xiaomi.smarthome:core E/MIIO: {"code":0,"interval":1,"max_number":100,"message":"ok","result":"true"}
08-18 15:52:09.023 32573-1622/com.xiaomi.smarthome:core D/CoreService: {"code":0,"interval":1,"max_number":100,"message":"ok","result":"true"}
08-18 15:52:09.024 32573-32691/com.xiaomi.smarthome:core I/STAT-SUCCESS: {"type":"result","key":"zdy.fj3.gi2.0k3","value":"{\"time\":159,\"errorcode\":0,\"model\":\"mxiang.cateye.mdb10\",\"did\":\"292198389\",\"extra\":\"\",\"key_name\":\"rpc_remote_result\",\"session\":1566114654737,\"order\":3}","extra":"","am":"mihome","uid":"14009822","time":1566114728}
08-18 15:52:09.050 3369-3369/? I/crash_dump32: obtaining output fd from tombstoned
08-18 15:52:09.053 979-979/? I//system/bin/tombstoned: received crash request for pid 2432
08-18 15:52:09.055 3369-3369/? I/crash_dump32: performing dump of process 2432 (target tid = 3366)
08-18 15:52:09.055 3369-3369/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-18 15:52:09.055 3369-3369/? A/DEBUG: Build fingerprint: 'Xiaomi/lithium/lithium:8.0.0/OPR1.170623.032/V10.2.1.0.OAHCNFK:user/release-keys'
08-18 15:52:09.056 3369-3369/? A/DEBUG: Revision: '0'
08-18 15:52:09.056 3369-3369/? A/DEBUG: ABI: 'arm'
08-18 15:52:09.056 3369-3369/? A/DEBUG: pid: 2432, tid: 3366, name: RenderThread  >>> com.xiaomi.smarthome:plugin0 <<<
08-18 15:52:09.056 3369-3369/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb74
08-18 15:52:09.056 3369-3369/? A/DEBUG: Cause: null pointer dereference
08-18 15:52:09.056 3369-3369/? A/DEBUG:     r0 00000000  r1 00000000  r2 c5832105  r3 00000000
08-18 15:52:09.056 3369-3369/? A/DEBUG:     r4 00000000  r5 c9899a00  r6 00000100  r7 00000078
08-18 15:52:09.056 3369-3369/? A/DEBUG:     r8 00000980  r9 c4c61c00  sl f450c335  fp 0000000b
08-18 15:52:09.056 3369-3369/? A/DEBUG:     ip c583cd60  sp bc39f908  lr f450c365  pc c5822fa0  cpsr 600f0030
08-18 15:52:09.066 3369-3369/? A/DEBUG: backtrace:
08-18 15:52:09.066 3369-3369/? A/DEBUG:     #00 pc 00020fa0  /system/lib/libRS_internal.so (_ZN7android12renderscript23rsi_ContextInitToClientEPNS0_7ContextE+11)
08-18 15:52:09.066 3369-3369/? A/DEBUG:     #01 pc 0000c363  /system/lib/libRScpp.so (_ZN7android3RSC2RS10threadProcEPv+46)
08-18 15:52:09.066 3369-3369/? A/DEBUG:     #02 pc 0004842f  /system/lib/libc.so (_ZL15__pthread_startPv+22)
08-18 15:52:09.066 3369-3369/? A/DEBUG:     #03 pc 0001b56d  /system/lib/libc.so (__start_thread+32)
08-18 15:52:09.108 32540-32551/com.xiaomi.smarthome I/zygote: Background concurrent copying GC freed 159524(12MB) AllocSpace objects, 7(140KB) LOS objects, 49% free, 12MB/24MB, paused 444us total 123.726ms
08-18 15:52:09.337 896-1079/? I/ThermalEngine: handle_thresh_sig: SS Id SKIN-SS-GOLD-AND-SILVER, Read xo_therm_buf 43000mC
08-18 15:52:09.517 896-1080/? I/ThermalEngine: handle_thresh_sig: HIS Id HISTORY-CPU4 Sensor tsens_tz_sensor8 Temp 61000
08-18 15:52:09.524 896-1080/? I/ThermalEngine: handle_thresh_sig: HIS Id HISTORY-CPU4 Sensor tsens_tz_sensor8 Temp 59000
08-18 15:52:09.593 896-1080/? I/ThermalEngine: handle_thresh_sig: HIS Id HISTORY-CPU4 Sensor tsens_tz_sensor8 Temp 61000

**Comment by 710224800** [comment]
日志显示很明显：android.content.res.Resources$NotFoundException: String resource ID #0x7f0c0194
