### ISSUE TITLE
米家公版摄像头插件: 直播连接 在 “91%准备开始播放” 之后不动 

### ISSUE THREAD

**Issue by zhaolios** [MiEcosystem/NewXmPluginSDK#118]
#### 环境
插件 model   loock.cateye.v02
已分享设备设备到 346378191，方便复现问题。设备名称 “小米米家智能猫眼”

#### 现象
直播连接，走百分比 走到   “91%准备开始播放”，就停住了，直播也连不上（等了3分钟左右）。

#### 期望

直播连接能成功

#### 其他的上下文/日志/截图

[long_text_2019-08-20-10-49-59.txt](https://github.com/MiEcosystem/NewXmPluginSDK/files/3518481/long_text_2019-08-20-10-49-59.txt)

**Comment by JiangxinNet** [comment]
有miss库的log么？

**Comment by zhaolios** [comment]
miss库的 log   过滤 关键词是什么？

**Comment by zhaolios** [comment]
这是 从UI出现 “91%准备开始播放”到 开始直播，用了 2分钟左右的日志（无过滤）。
[long_text_2019-08-20-19-20-28.txt](https://github.com/MiEcosystem/NewXmPluginSDK/files/3520277/long_text_2019-08-20-19-20-28.txt)

**Comment by JiangxinNet** [comment]
miss log好像在手机中的文件管理下面，直接往一下划，找到miss.log
