### ISSUE TITLE
被分享的成员操作权限问题：1、可以进入通用设置进行删除设备 2、可以删除录像记录

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#119]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题

#### 现象

请使用 logcat 导出所有进程的 log
简单明了地描述一下实际的现象。

#### 期望

1、关闭通用设置入口 不允许删除设备 2.不允许成员删除录像记录

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
分享用户分为：允许控制，和 仅可查看 之分，产品需求如此，不是问题
