### ISSUE TITLE
猫眼首页，点击底部的人脸管理，无响应

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#120]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
三星s6机型  Android6.0  wifi下
#### 期望

点击人脸管理 跳转对应的页面

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
未复现此问题，线下已对过，请更新最新代码后，重新验证

**Comment by liubing8896** [comment]
使用新版本 验证通过
