### ISSUE TITLE
没有购买云存的前提下，移动侦测设置页面，打开人脸识别开关时，没有给出提示

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#121]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
#### 现象
进入设置  移动侦测设置 打开人脸开关 

#### 期望

提示 需要开通云存会员后才可使用

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
请更新最新代码后，重新验证

**Comment by liubing8896** [comment]
验证可以了
