### ISSUE TITLE
打开省电模式后，猫眼首页点击查看实时画面，没有响应也没有任何提示

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#122]
#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题

#### 现象
先去设置 打开省电模式  回到首页 点击查看实时画面  没有响应 也没提示 

#### 期望

弹框给出提示：设备不在线，请检查省电模式开关是否处于打开状态，如果已打开，请等待下次设备被唤醒

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
未复现此问题，线下已对过

**Comment by liubing8896** [comment]
这个问题我们开发已经处理
