### ISSUE TITLE
点击收到的停留或者有人经过的推送消息，没有跳转到对应的录像详情页

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#123]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题

#### 期望
直接跳转到对应报警消息的详情页 播放视频
简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
未复现此问题，线下已对过

**Comment by liubing8896** [comment]
新版本上验证可以
