### ISSUE TITLE
查看报警录像时，双击屏幕或者双指操作都不能放大和缩小画面

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#124]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
#### 现象
点击一个报警录像查看 双击画面 或者双指操作 画面不会被放大或缩小

#### 期望
这些手势可以实现画面缩放

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
斩不支持此feature，如需要请差异化处理
