### ISSUE TITLE
手机无网络时，查看设备动态的录像，页面一直加载黑屏

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#125]
---
#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
三星s6机型 Android6.0 wifi下

#### 现象

进入猫眼首页 将手机断网 点击一个录像查看 一直加载黑屏
#### 期望

给出无网络或者检查网络的提示

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
会修复，请下版验证
