### ISSUE TITLE
无网络状态下，进入猫眼首页，点击查看实时画面，提示不合理

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#126]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
插件 model 是什么
使用的哪个方法
请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象

请使用 logcat 导出所有进程的 log
简单明了地描述一下实际的现象。

#### 期望

提示网络不可用 或者检查网络连接

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/54298908/63401294-5ddc9e00-c409-11e9-904b-d0936d1192de.png)

![微信图片_20190821114759](https://user-images.githubusercontent.com/54298908/63401351-911f2d00-c409-11e9-97f4-73db5bfeb773.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
会修复，请下版验证

**Comment by liubing8896** [comment]
这个问题 我们开发这边已经处理了 修改成了 当无网络时 查看实时画面 提示当前无网络 请稍后重试
