### ISSUE TITLE
设置页面，点击使用帮助，页面显示空白

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#127]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
三星s6机型 Android6.0 wifi下

#### 期望

应该包含常见的QA

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/54298908/63401520-199dcd80-c40a-11e9-991d-16c25bdcf769.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
需要生态链公司自行配置，请咨询相关产品经理
