### ISSUE TITLE
语音快捷回复页面，新增一条语音快捷回复，退出到直播页面，再次进入语音快捷页面一直提示获取数据

### ISSUE THREAD

**Issue by liubing8896** [MiEcosystem/NewXmPluginSDK#128]
---

#### 环境
插件 model loock.cateye.v02
可以使用测试账号 15910550249 密码12345678q复现问题
三星s6机型 Android6.0 wifi下

#### 现象

一直加载数据

#### 期望

进入语音快捷回复页面 不用一直加载

#### 其他的上下文/日志/截图

![image](https://user-images.githubusercontent.com/54298908/63401668-bf513c80-c40a-11e9-8c74-bb5bc12b2621.png)

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by 710224800** [comment]
未复现，线下已经对过这个问题，如有问题请直接群里咨询
