### ISSUE TITLE
建议将gradle版本更新

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/NewXmPluginSDK#13]
1.建议将gradle版本更新至3.0.1，以及gradle脚本打包的方法，在3.0上有所改变。
2.更新所有的support包，说明米家app使用的是什么版本，插件app不要逾越就好。

**Comment by cjsh** [comment]
兄弟，gradle脚本打包问题怎么解决的啊

**Comment by wangchongwhut** [comment]
gradle脚本已更新。现在插件是通过单独的DexClassLoader加载的，可以自行选择support版本。
