### ISSUE TITLE
米家云端API没有改和查的功能

### ISSUE THREAD

**Issue by pengchengcool** [MiEcosystem/NewXmPluginSDK#130]
米家用户管理，增删改查的功能是如何与服务器同步的。是否用的米家云端API，还是需要我们自己搭建用户管理的服务呢？

![7cd5367d0e937f28736649363324d8a](https://user-images.githubusercontent.com/50361047/63917054-45edc580-ca6c-11e9-926b-ddf73734f6a7.jpg)

before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
插件 model 是什么
使用的哪个方法
请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象

请使用 logcat 导出所有进程的 log
简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by zanetti4** [comment]
@lvjie0519 请吕杰帮助查看

**Comment by lvjie0519** [comment]
@pengchengcool   请问一下，用户管理这个界面是米家APP这边的 还是  你那边插件的页面？ 如果是米家APP的页面，请提供下具体是哪个api ？   理论上应该都是走的米家这边的云端，插件方无需自己搭建云服务。

**Comment by pengchengcool** [comment]
我截图的这个是米家指纹锁插件的界面，可以修改用户名，删除单个用户。我们自己插件里面要做这个功能，没有修改和删除的接口只找到上传的接口。

现有如下几个问题也需要咨询下：

1.锁端开门等日志记录，如何通过手机上传到小米云端服务器
方式一：锁端Ble->米家插件Ble->米家云端接口
方式二：锁端Ble->米家app网关

2.**/user/set_user_device_data**，数据上报如何避免重复数据上传，需要客户端来保证吗？服务端是否有什么机制

3.端用户数据查询接口 **/user/get_user_device_data**，如何实现分页查询呢

4.米家扩展程序存取跟设备相关数据，设备解绑（被用户删除）时，数据会被服务器自动清理。
但是重新绑定设备之后还是可以通过**/user/get_user_device_data**获取到数据

**Comment by lvjie0519** [comment]
关于 get_user_device_data 相关服务接口，可以参考如下文档

https://iot.mi.com/new/guide.html?file=08-%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/03-%E5%AD%98%E5%82%A8/02-%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8-SDS
