### ISSUE TITLE
BLE_SECURE 从SDK2.1.11升级为SDK2.2.5后出现连接超时的现象

### ISSUE THREAD

**Issue by xiaoyongge** [MiEcosystem/NewXmPluginSDK#131]
蓝牙门锁项目
SDK2.1.11：
连接正常。

更新为最新的SDK2.2.5后：
米家锁如何在首次配对时，弹出设置6位安全密码的框，设置安全密码为111111后进入连接状态；门锁设备大概在3秒左右退出连接，APP在30S左右显示添加失败：

![image](https://user-images.githubusercontent.com/12733226/64319527-2ec05200-cfef-11e9-8d75-e54dcc47c3d5.png)

麻烦安排解决这个问题，问题必现。

before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
插件 model 是什么
使用的哪个方法
请分享设备或绑定设备到 346378191，方便复现问题。

#### 现象

请使用 logcat 导出所有进程的 log
简单明了地描述一下实际的现象。

#### 期望

简单明了地描述一下期望的表现。

#### 其他的上下文/日志/截图

提供更多的上下文，有日志或者截图更好。

#### 尝试过的解决办法

尝试过哪些操作？

**Comment by xiaoyongge** [comment]
APP版本为最新的。

**Comment by pencilCool** [comment]
1请提供一下app 的本地日志
2安卓有误类似问题？

**Comment by pencilCool** [comment]
在jira 工单上更进这个问题了。issue 先关闭。
