### ISSUE TITLE
设备休眠后后APP显示离线

### ISSUE THREAD

**Issue by Kevin-zhongyx** [MiEcosystem/NewXmPluginSDK#135]
#### 环境
linux 环境
使用miio_client
"model":"ydhome.cateye.pr1"
属于非保活门铃
#### 现象
![image](https://user-images.githubusercontent.com/53296204/64403075-cbdfc100-d0a9-11e9-9599-d771ab534ff0.png)
设备断电休眠之后APP提示设备已离线。同样的丁铃的设备并不会提示离线。
设备端开机起来后有上报props online 是1 。

#### 期望
设备断电休眠后APP上看到是在线

**Comment by 710224800** [comment]
需要服务端配置，请咨询产品经理林晶
