### ISSUE TITLE
设备主动获取OTA信息

### ISSUE THREAD

**Issue by Kevin-zhongyx** [MiEcosystem/NewXmPluginSDK#136]
before issue：（不用回答）
### 是否尝试搜索issue？

---

#### 环境
linux 环境
使用miio_client
"model":"ydhome.cateye.pr1"
属于非保活门铃

#### 现象
目前OTA信息都是由APP端点击升级之后通过OT通道收到OTA信息。

#### 期望

希望设备能通过某种方式可以主动从OT通道获取到OTA信息

**Comment by 710224800** [comment]
请先咨询产品经理林晶
