### ISSUE TITLE
关于common_ui的建议

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/NewXmPluginSDK#15]
建议你们写commom_ui的控件的时候考虑一下使用者的感受，没有任何修改方法，资源文件全是写死，也没注释，建议参考一下github其它开源控件，这对我们使用者来说，使用之前得先理解这个控件的实现，项目时间紧促这很耗时间。

**Comment by wongzy** [comment]
感谢，我们后期会慢慢完善的。
