### ISSUE TITLE
当APP成功发送消息给设备后，设备的成功回调会延迟好几秒

### ISSUE THREAD

**Issue by xufazi** [MiEcosystem/NewXmPluginSDK#16]
当APP成功发送修改属性的消息给设备后，在控制台上会输入“rpc data time out, retry 1”、“rpc data time out, retry 2”这样的信息；
延迟个2S左右后（情况严重的话7-8S）APP才会收到设备修改成功的回调，这会是什么情况导致的呢？

错误信息：
`java.net.ScoketTimeoutExceptionjava.net.SocketTimeoutException`

`at com.xiaomi.miio.MiioLocalAPI.a(MiioLocalAPI.java:91)`
`at com.xiaomi.miio.MiioLocalAPI.a(MiioLocalAPI.java:592)`
`at com.xiaomi.miio.MiioLocalAPI.b(MiioLocalAPI.java:708)`
`at com.xiaomi.miio.MiioLocalAPI$11.run(MiioLocalAPI.java:654)`

**Comment by wangchongwhut** [comment]
使用callMethod方法访问设备属性的时候，如果设备与手机在同一个局域网，会发送udp命令给设备，这种情况异常下可能会有延迟。你们可以使用callMethodFromCloud方法，这个方法直接通过云端访问设备，会更稳定。
