### ISSUE TITLE
写返回的value

### ISSUE THREAD

**Issue by H282650** [MiEcosystem/NewXmPluginSDK#19]
设备端写返回给我的是19个字节，但是我通过XmBluetoothManager.ACTION_CHARACTER_WRITE，拿到的只有2个字节

**Comment by H282650** [comment]
写什么返回什么，比如写a返回a

**Comment by wangchongwhut** [comment]
XmBluetoothManager.ACTION_CHARACTER_WRITE监听的本来就是你写的数据结果。

XmBluetoothManager.ACTION_CHARACTER_CHANGED监听的才是设备notify返回的数据。

**Comment by H282650** [comment]
那我每个通知都要按照serverUUID 来注册了，notifyData（），其返回值是code是什么值表示成功，我日志发现返回-1也可以拿到通知的信息。
registerCharacterChanged方法什么作用？
