### ISSUE TITLE
Android Studio3.0.1 Gradle4.4运行工程出现这个问题

### ISSUE THREAD

**Issue by cjsh** [MiEcosystem/NewXmPluginSDK#21]
Error:FAILURE: Build failed with an exception.

* Where:
Script 'D:\AndroidSutidoWorkSpace\NewXmPluginSDK-master\NewXmPluginSDK-master\plug.gradle' line: 183

* What went wrong:
Execution failed for task ':plugProject:moyu_washer:assembleDebug'.
> Process 'command 'D:\BaiduYunDownload\luna_adt\luna_adt\sdk\platform-tools\adb'' finished with non-zero exit value 1

**Comment by zhaomingxiaomi** [comment]
发一下命令行的完整输出吧
