### ISSUE TITLE
report time issues

### ISSUE THREAD

**Issue by H282650** [MiEcosystem/NewXmPluginSDK#23]
1.“/user/set_user_device_data”批量上传历史数据的参数之一time是指哪个时间戳，某条历史数据的时间或者上传数据的时间；

2.“/user/get_user_device_data”读取历史数据的参数time_start、time_end,如果要获取某天的数据，可以是time_start=currentTime ; time_end =  currentTime-24小时；如果是某个月，或者某年如何传参？获取多少个历史数据？ 获取的历史数据哪个作为参数

**Comment by zhaomingxiaomi** [comment]
1.客户端只提供了get_suer_device_data来批量查询设备的上传属性
2.如果某个月就计算一下起始和结束日期的时间戳，SimpleDateFormat就可以做

**Comment by hanbingwuxie** [comment]
如无疑问请关闭下 issue谢谢~
