### ISSUE TITLE
检查固件版本

### ISSUE THREAD

**Issue by H282650** [MiEcosystem/NewXmPluginSDK#24]
我看demo和文档上描述的不一样，不知道哪个API能获取到当前版本和最新版本：
1.mDevice.checkDeviceUpdateInfo();--获取当前版本和最新版本；

2.getBluetoothFirmwareVersion（）；--获取当前版本；

3.getBluetoothFirmwareUpdateInfo（）； -- 获取最新版本和downloadUrl;

问题是：第1个方法能检查出当前版本和最新版本吗？我测试不能...

**Comment by zhaomingxiaomi** [comment]
如果是wifi设备的话，用第一个接口检查固件升级，后面两个检查的是蓝牙固件升级

**Comment by enstone88** [comment]
@H282650 您好，你们的固件是关于蓝牙的吗？我们正好有这个需求，能请教下吗？关于升级方面的问题吗？

**Comment by H282650** [comment]
我不是做硬件的，我是做APP端的

**Comment by enstone88** [comment]
您好，我也是做app的，安卓这块的 我自己建的群 859038200

在 2018-09-29 12:37:23，"H282650" <notifications@github.com> 写道：
我不是做硬件的，我是做APP端的
