### ISSUE TITLE
update设备的UI

### ISSUE THREAD

**Issue by H282650** [MiEcosystem/NewXmPluginSDK#26]
BleUpgrader.showPage(int page,Bundle data),这个方法不公开，我不知道怎么按需求修改里面的UI，比如page = PAGE_LOADING时，我怎么修改里面的progressDialog样式，和界面展示文字

**Comment by wangchongwhut** [comment]
蓝牙设备的固件升级页面样式是统一的，只能更新升级进度，以及升级结果。

**Comment by H282650** [comment]
你加我什么？
给你段代码，你看下应该知道了：
public final BleUpgrader mBleUpgrader = new BleUpgrader() {
    @Override
    public String getCurrentVersion() throws RemoteException {
        return mCurrentVersion;
    }

    @Override
    public String getLatestVersion() throws RemoteException {
        return mNewestVersion;
    }

    @Override
    public String getUpgradeDescription() throws RemoteException {
        return "";
    }

    @Override
    public void startUpgrade() throws RemoteException {
        mHandler.sendEmptyMessage(MSG_UPDATE);//点击小米更新界面的update按钮跳转到自定义更新界面
    }


    @Override
    public void onActivityCreated(Bundle bundle) throws RemoteException {
        if (StringUtil.isEmpty(mNewestVersion)) {
            Intent intent = new Intent();
            intent.putExtra("mCurrent", mCurrentVersion);
            startActivity(intent, CallBackNonActivity.class.getName());//如果获取版本号null,跳转到自定义提示界面
        } else {
            mHandler.postDelayed(new Runnable() {

                @Override
                public void run() {

                    if (!mCurrentVersion.equals(mNewestVersion)) {
                        mBleUpgrader.showPage(XmBluetoothManager.PAGE_CURRENT_DEPRECATED, null);
                    } else {
                        mBleUpgrader.showPage(XmBluetoothManager.PAGE_CURRENT_LATEST, null);
                    }
                }
            }, 1000);

        }
    }

};

**Comment by enstone88** [comment]
@H282650 分享一个qqq群号给你，我创建的859038200

**Comment by H282650** [comment]
米家的项目我已经不做了，插件相关的东西我基本都忘记了，进群也帮助不了你们啥了

**Comment by enstone88** [comment]
@H282650 好的，谢谢你，假日快乐
