### ISSUE TITLE
小米开发平台Android发包问题

### ISSUE THREAD

**Issue by H282650** [MiEcosystem/NewXmPluginSDK#28]
有个问题要问下小米同学们：Android：当向小米开发平台上传插件包（地址：https://iot.mi.com/productDetail_new.html#/plugin/plugin?model=yuemee.airmonitor.mhfd1），小米APP绑定的插件再插件列表点击无反应打不开？这个平台提交的插件包是debug版本的吗？还是按你们给的文档从build>output>apk拿？

**Comment by H282650** [comment]
有个问题想请教：我的插件里面有调用反射获取主程序的activity,用adb install是正常运行，发签名包到云端不执行；为什么？主要代码如下：
//获取指定的activity,nima
    public static Activity getCurrentActivity() {
        try {
            Class activityThreadClass = Class.forName("android.app.ActivityThread");
            Object activityThread = activityThreadClass.getMethod("currentActivityThread").invoke(
                    null);
            Field activitiesField = activityThreadClass.getDeclaredField("mActivities");
            activitiesField.setAccessible(true);
            Map activities = (Map) activitiesField.get(activityThread);
            for (Object activityRecord : activities.values()) {
                Class activityRecordClass = activityRecord.getClass();

                Field activityField = activityRecordClass.getDeclaredField("activity");
                activityField.setAccessible(true);
                Activity activity = (Activity) activityField.get(activityRecord);
                if (activity.getComponentName().getClassName().equals("com.xiaomi.smarthome.miio.activity.BleUpgradeActivity")) {
                    return activity;
                }


            }
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return null;
    }

**Comment by wangchongwhut** [comment]
不要通过反射调用BleUpgradeActivity，这里面涉及到一些多进程切换会有问题，使用我们封装的BLE固件更新接口显示相关UI
