### ISSUE TITLE
米家扩展程序自动连接的问题

### ISSUE THREAD

**Issue by M-Dragon** [MiEcosystem/NewXmPluginSDK#29]
已经链接过的插件设备，退出后10s自动断开连接，那么再次进入插件设备页面时，如何阻止弹出“点击连接”的弹窗而自动连接呢？请问有没有对应的API可用？谢谢。

**Comment by wangchongwhut** [comment]
你们可以在小米IoT开发平台关闭扩展程序内离线提醒。
