### ISSUE TITLE
Android 添加 设备 “扩展程序初始化失败”这个问题怎么排查?

### ISSUE THREAD

**Issue by enstone88** [MiEcosystem/NewXmPluginSDK#31]

**Comment by zhaomingxiaomi** [comment]
提交下Log

**Comment by enstone88** [comment]
[1.log](https://github.com/MiEcosystem/NewXmPluginSDK/files/2276295/1.log)
设备添加成功后，选择位置界面 点击 “立即使用”


无法跳转，一直卡 “获取数据中，，，”

**Comment by wangchongwhut** [comment]
你需要先在小米IoT开发者平台上传Android扩展程序，并且设置成白名单可见。添加设备完成后，才能正常下载和使用扩展程序。

**Comment by zhaomingxiaomi** [comment]
com.ydhome.lockm2silver.android.MessageReceiver这个receiver没有继承com.xiaomi.smarthome.device.api.IXmPluginMessageReceiver
