### ISSUE TITLE
我们使用官方demo,在app发送开门指令时,蓝牙的处理流程

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/NewXmPluginSDK#32]
app发送开门指令的时候,蓝牙协议栈抛上来了两个事件0x50和0x51,为什么会上抛两个事件?
蓝牙侧,如何和米家app交互 的

**Comment by wangchongwhut** [comment]
XmBluetoothManager里面的蓝牙接口只是对系统蓝牙接口进行了封装，没有修改传输的数据，你可以和你们的硬件工程师联调下，找下这两个事件的含义。
