### ISSUE TITLE
关于设备离线后扩展程序无法点击

### ISSUE THREAD

**Issue by Zhaoyuntao** [MiEcosystem/NewXmPluginSDK#33]
设备离线时进入扩展程序, 除了title区域能点击外, 其他UI区域接收不到点击事件, 请问如何设置离线调试UI?

**Comment by zhaomingxiaomi** [comment]
开放平台上可以配置离线可进入

**Comment by Zhaoyuntao** [comment]
是米家扩展程序管理->基础配置里面的那个扩展程序内离线提醒吗, 我设置为否之后, 离线进入扩展程序还是无法点击UI

**Comment by Zhaoyuntao** [comment]
对了,最新版的米家调试APP点右上角的加号会闪退, 不知道为什么.

**Comment by wangchongwhut** [comment]
闪退是调试版本出现的bug，已经修复。
