### ISSUE TITLE
米家智能插线板 android端倒计时操作接口报错

### ISSUE THREAD

**Issue by zhjsheng** [MiEcosystem/NewXmPluginSDK#34]
产品model为：zimi.powerstrip.v2 | 米家智能插线板 | 10007

目前用的apilevel为58，在取消倒计时和重设倒计时都会有下面的错误，
9-03 19:25:16.203 5204-5268/? V/xiaomi: [Thread:8462] JOB: do reconnect..
09-03 19:25:16.212 5204-5268/? V/xiaomi: [Thread:8462] update the connection status. disconnected -> connecting : ERROR_OK 
09-03 19:25:16.234 5204-5268/? V/xiaomi: [Thread:8462] begin to connect to 118.26.252.11:5222
09-03 19:25:16.274 5204-5268/? V/xiaomi: [Thread:8462] tcp connected
09-03 19:25:16.281 5204-5268/? V/xiaomi: [Thread:8462] [slim] open conn: andver=26 sdk=36 hash=eO8RanrLOB7H8iis tz=8:0 Model=EVA-AL10 os=528(C00)
09-03 19:25:16.281 5204-5268/? V/xiaomi: [Thread:8462] connected to 118.26.252.11:5222 in 47
09-03 19:25:16.309 5204-7046/? V/xiaomi: [Thread:8489] setChallenge hash = cfe642cd
09-03 19:25:16.310 5204-7046/? V/xiaomi: [Thread:8489] update the connection status. connecting -> connected : ERROR_OK 
09-03 19:25:16.322 5204-7046/? V/xiaomi: [Thread:8489] [Slim] CONN: host = e688
09-03 19:25:16.322 5204-5268/? V/xiaomi: [Thread:8462] JOB: bind the client. 5
09-03 19:25:16.322 5204-5268/? V/xiaomi: [Thread:8462] update the client 5 status. unbind->binding unknown ERROR_OK null null
09-03 19:25:16.323 5204-5268/? V/xiaomi: [Thread:8462] [Slim]: bind id=tyHWP-17
09-03 19:25:16.363 5204-5268/? V/xiaomi: [Thread:8462] SMACK: channel bind succeeded, chid=5
09-03 19:25:16.364 5204-5268/? V/xiaomi: [Thread:8462] update the client 5 status. binding->binded OPEN ERROR_OK null null
09-03 19:25:16.365 5204-5268/? V/xiaomi: [Thread:8462] JOB: notify job
09-03 19:25:16.833 1109-1910/? V/WindowManager: Adding Window{5b754b4 u0 com.xiaomi.smarthome/com.xiaomi.smarthome.frame.plugin.runtime.activity.PluginHost

**Comment by wangchongwhut** [comment]
上面的错误信息不是米家APP报的。你用米家APP调试版测试，复现问题后，把所有的log抓取到一个文件里上传上来。

**Comment by hanbingwuxie** [comment]
会返回什么错误？
