### ISSUE TITLE
米家调试版apk无法安装插件，签名错误

### ISSUE THREAD

**Issue by supereye318** [MiEcosystem/NewXmPluginSDK#36]
红米6A手机，装的GitHub上下的米家调试版，电脑上装的Android studio 3.2 往手机上装调试扩展程序的时候报错，sd卡本地安装插件失败，签名错误，运行自带的实例程序PluginDemo，也是这样，大致是这个意思，请问这是怎么回事，该怎么设置？

**Comment by wongzy** [comment]
您好，能提供下具体的信息吗？比如说log

**Comment by hanbingwuxie** [comment]
1.校验下手机是否打开文件 读写权限
2.检查你插件的MiHomeDeveloperId 是否配置 插件签名是文件是否正确
