### ISSUE TITLE
米家中 应用通过服务器获取不到设备电量等信息 

### ISSUE THREAD

**Issue by 18792576258** [MiEcosystem/NewXmPluginSDK#39]
get_user_device_data中已经获取到了事件信息，通过文档试了好多没有获取到电量等信息，具体是哪个接口和接口中的参数能否说下

**Comment by hanbingwuxie** [comment]
你们是什么设备呢，电量信息应该是向设备发送RPC命令请求回来了的吧，XmPluginHostApi callMethodFromCloud
