### ISSUE TITLE
Redmi 6 Pro  gradlew installpackageName无法成功！

### ISSUE THREAD

**Issue by lilfei** [MiEcosystem/NewXmPluginSDK#45]
红米6 pro MIUI 10稳定版 10.0.2.0 gradlew installpackageName，命令执行完成，但手机端并未装上插件包。
![_20181008130233](https://user-images.githubusercontent.com/15316544/46593221-a98d9e00-cafc-11e8-94fd-a88c2144c0a8.png)
USB调试，开发者模式都已打开。MIUI优化已关闭。
以前使用的别的手机执行正常。

**Comment by wangchongwhut** [comment]
最近米家app升级了targetSdkVersion到26，通过adb shell启动app的命令变了，可以更新下sdk同步最新的命令脚本

**Comment by lilfei** [comment]
got it !   thx @zhaomingxiaomi @wangchongwhut
