### ISSUE TITLE
调用XmPluginHostApi.instance().getSettingLocale()引起crash,如何处理

### ISSUE THREAD

**Issue by zhjsheng** [MiEcosystem/NewXmPluginSDK#46]
![image](https://user-images.githubusercontent.com/4638162/46651300-1d4daa80-cbd2-11e8-96fd-992ba418f21a.png)
![image](https://user-images.githubusercontent.com/4638162/46651325-348c9800-cbd2-11e8-834d-5133c2f8411a.png)

**Comment by hanbingwuxie** [comment]
这个crash必现么，app 版本多少？我们排查下，Local 也可以通过另一种方式 获取 activity().getResorse().getConfiguration().locale
