### ISSUE TITLE
项目运行不起来，Android Studio 3.1.2  gradle 3.0.0

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#49]
Error: Activity class {com.xiaomi.smarthome/com.xiaomi.smarthome.SmartHomeMainActivity} does not exist.

**Comment by wangchongwhut** [comment]
是不是手机没有安装米家app，你可以自己通过adb命令试下能不能启动米家app：adb shell am start com.xiaomi.smarthome/.SmartHomeMainActivity

**Comment by Tywei24** [comment]
嗯嗯，已解决。谢谢
