### ISSUE TITLE
扩展程序跑不起来

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#50]
报错：Process 'command 'C:\Users\Tywei\AppData\Local\Android\Sdk\platform-tools\adb'' finished with non-zero exit value 1

**Comment by wangchongwhut** [comment]
现在是通过adb命令来启动扩展程序的，你看下是不是你的手机没有开调试模式，你可以自己通过下面的命令试下能否启动米家APP：adb shell am start com.xiaomi.smarthome/.SmartHomeMainActivity
