### ISSUE TITLE
偶现好几次发一条BLE指令，收到多次XmBluetoothManager.ACTION_CHARACTER_WRITE广播

### ISSUE THREAD

**Issue by lovelikeaiko** [MiEcosystem/NewXmPluginSDK#51]
偶现好几次发一条BLE指令，收到多次XmBluetoothManager.ACTION_CHARACTER_WRITE广播。硬件也确实收到了多次指令。一旦出现这种情况，就一直这样。只有关闭app才行。

**Comment by wangchongwhut** [comment]
每次通过XmBluetoothManager.getInstance().write()写成功后，底层都会再发送一条XmBluetoothManager.ACTION_CHARACTER_WRITE广播出来。硬件也收到了多条指令，说明是扩展程序发送了多个write命令，你们检查下代码，是不是重复发送了。
