### ISSUE TITLE
设置菜单openMoreMenu相关问题

### ISSUE THREAD

**Issue by aaazxc43891221a** [MiEcosystem/NewXmPluginSDK#52]
1. 未找到打开“使用许可”和“隐私条款”Item接口；
2. 添加自定义接口后Toolbar 的title由 "通用设置" 变为 “更多”，是否有接口能修改title；
3. 自定义Item时默认item（设置、设备共享、删除设备、使用帮助）和新建的自定义Item（StringMenuItem、IntentMenuItem、SlideBtnMenuItem、InfoMenuItem、BleMenuItem）这种Item并存时，Item margin值不统一。

**Comment by wangchongwhut** [comment]
1）你通过openMoreMenu2()打开菜单时，打开开关putExtra("enableRemoveLicense", true);把使用协议和隐私条款通过putExtra("licenseContentHtml", "")和putExtra("privacyContentHtml", "")传递过来，具体可以参考Demo工程实现

2）能否说下你调用的哪个方法添加自定义接口，感觉是添加自定义菜单的方法不对

3）能否提供下截图，我们详细看下UI

**Comment by aaazxc43891221a** [comment]
1) 先上代码
  ```
ArrayList<IXmPluginHostActivity.MenuItemBase> items = new ArrayList<IXmPluginHostActivity.MenuItemBase>();
                IXmPluginHostActivity.BleMenuItem bleMenu = IXmPluginHostActivity.BleMenuItem.newUpgraderItem(mBleUpgrader);
                Log.i("pkg", mPluginPackage.getPackageName());
                items.add(bleMenu);

 //使用html方式
Intent intent = new Intent();
intent.putExtra("enableRemoveLicense", true);
intent.putExtra("licenseContentHtml", getHtmlFromAssets("privacy_policy.html"));
intent.putExtra("privacyContentHtml", getHtmlFromAssets("software_permission.html"));
hostActivity().openMoreMenu2(items, true, SUBMENU1_CODE, intent);
```

Apk使用的是
http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_apk_ac23ddc8b206fa432a11ce088f9a2719.apk
这样修改目前仍然没有出现隐私政策和使用条款入口，请问这是否最新的apk下载路径
![default](https://user-images.githubusercontent.com/20717199/47281219-812d9580-d60c-11e8-9c79-e21682791376.jpg)
![default](https://user-images.githubusercontent.com/20717199/47281229-8d195780-d60c-11e8-93aa-44a461d5e0fc.jpg)



2）  代码：
```
 ArrayList<IXmPluginHostActivity.MenuItemBase> items = new ArrayList<IXmPluginHostActivity.MenuItemBase>();

 IXmPluginHostActivity.StringMenuItem stringMenuItem = new
XmPluginHostActivity.StringMenuItem();
stringMenuItem.name = "test string menu";
items.add(stringMenuItem);
hostActivity().openMoreMenu(items, true, SUBMENU1_CODE, null);
```


2、3问题见图片附件

**Comment by aaazxc43891221a** [comment]
1) 先上代码
  ```
ArrayList<IXmPluginHostActivity.MenuItemBase> items = new ArrayList<IXmPluginHostActivity.MenuItemBase>();
                IXmPluginHostActivity.BleMenuItem bleMenu = IXmPluginHostActivity.BleMenuItem.newUpgraderItem(mBleUpgrader);
                Log.i("pkg", mPluginPackage.getPackageName());
                items.add(bleMenu);

 //使用html方式
Intent intent = new Intent();
intent.putExtra("enableRemoveLicense", true);
intent.putExtra("licenseContentHtml", getHtmlFromAssets("privacy_policy.html"));
intent.putExtra("privacyContentHtml", getHtmlFromAssets("software_permission.html"));
hostActivity().openMoreMenu2(items, true, SUBMENU1_CODE, intent);
```

Apk使用的是
http://cdn.cnbj0.fds.api.mi-img.com/miio.files/commonfile_apk_ac23ddc8b206fa432a11ce088f9a2719.apk
这样修改目前仍然没有出现隐私政策和使用条款入口，请问这是否最新的APK路径

2）  代码： ```
ArrayList<IXmPluginHostActivity.MenuItemBase> items = new ArrayList<IXmPluginHostActivity.MenuItemBase>();

 IXmPluginHostActivity.StringMenuItem stringMenuItem = new
XmPluginHostActivity.StringMenuItem();
stringMenuItem.name = "test string menu";
items.add(stringMenuItem);
hostActivity().openMoreMenu(items, true, SUBMENU1_CODE, null);
```

附上2、3问题截图
![Uploading 米家.jpg…]()

**Comment by wangchongwhut** [comment]
1）标题栏是没法自定义的，目前如果有自定义的菜单，标题栏就会改为“更多”，后期我们会优化下，标题栏统一都是“通用设置”
2）自定义Item的样式后期也会优化，与其他的样式保持一致
3）设置隐私菜单参考如下：
ArrayList<IXmPluginHostActivity.MenuItemBase> items = new ArrayList<IXmPluginHostActivity.MenuItemBase>();
              IXmPluginHostActivity.BleMenuItem bleMenu = IXmPluginHostActivity.BleMenuItem.newUpgraderItem(mBleUpgrader);
              Log.i("pkg", mPluginPackage.getPackageName());
              items.add(bleMenu);

// 这个intent控制的是第一级下拉菜单的样式
Intent intent = new Intent();

// 这个intent控制的是通用设置里面的菜单
Intent commonSetting = new Intent();
//使用html方式
commonSetting.putExtra("enableRemoveLicense", true);
commonSetting.putExtra("licenseContentHtml", getHtmlFromAssets("privacy_policy.html"));
commonSetting.putExtra("privacyContentHtml", getHtmlFromAssets("software_permission.html"));

hostActivity().openMoreMenu2(items, true, SUBMENU1_CODE, intent, commonSetting);

**Comment by aaazxc43891221a** [comment]
已解决，感谢！
