### ISSUE TITLE
米家测试版从5.4.14及以后，不能通过USB安装扩展程序到Android8.0以上的手机了

### ISSUE THREAD

**Issue by hhcc1992** [MiEcosystem/NewXmPluginSDK#53]
以前都可以，现在不行了，米家5.4.11测试版可以，使用米家5.4.14及以后测试版的时候，Android6.0的手机也可以，8.0不行，测试手机小米mix，提示的是BUILD SUCCESSFUL in 28s，Task execution finished 'installHhcc_plantmonitorDebug'.没有弹出安装成功，点进去看效果也确实没有安装成功

**Comment by wangchongwhut** [comment]
需要更新下SDK里面的plug.gradle脚本，最新米家app更新了targetSdkVersion，通过adb命令调起米家app的方式变了。

**Comment by PioneerVM** [comment]
请问楼主解决了吗，我用的红米6，系统是Android 9 ，也替换了sdk里面的plug.gradle脚本，但是为什么仍然安装不上插件呢？

**Comment by PioneerVM** [comment]
楼主解决没，我用的红米6 ，系统是Android 9 更新了下最新的 plug.gradle，但是仍然不能装插
