### ISSUE TITLE
插件和设备交互中，突然断开连接。

### ISSUE THREAD

**Issue by flyer1111** [MiEcosystem/NewXmPluginSDK#58]
![image](https://user-images.githubusercontent.com/42274809/48121336-9e6e8f00-e2af-11e8-93b1-c2107d776ba5.png)
设备收到disconnect 13 ，查看手册时手机端断开连接，帮忙看一下手机侧为什么断开连接

**Comment by flyer1111** [comment]
disconnect13 时手机主动断开连接，不是锁端蓝牙主动断开连接的。

**Comment by zanetti4** [comment]
请问该问题解决了吗？涉及到的手机系统是什么？
