### ISSUE TITLE
米家调试APK无法替换本地run的插件

### ISSUE THREAD

**Issue by stephen-wu-yuan** [MiEcosystem/NewXmPluginSDK#59]
从git上下载了commonfile_apk_a3282f4ea6d71b4ca6ada007ba454d8c.apk，安装到手机后，run本地的插件，发现不管本地插件怎么改，run后，米家apk用的好像一直是网上down的插件，米家apk已经给了sd读写权限。请帮忙解决下，谢谢

**Comment by wangchongwhut** [comment]
1）先同步下最新的github sdk
2）run之后米家app有相关toast提示没？

**Comment by stephen-wu-yuan** [comment]
谢谢，同步最新的sdk就OK了
