### ISSUE TITLE
通用设置页面

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#60]
没有找到“添加桌面快捷方式”和“设备时区“”隐藏条目的api

同时在给通用设置界面添加自定义的条目时候。如何才能控制添加的位置
![image](https://user-images.githubusercontent.com/29192190/48704937-d3290180-ec32-11e8-87cc-7e02a66cb66d.png)
把使用条款和华氏度添加到反馈后面，并且不要标题

**Comment by hanbingwuxie** [comment]
"timezone_enable" 设备时区
"shortcut_enable" 桌面快捷方式

**Comment by Tywei24** [comment]
多谢哈，我还想把我自定义的菜单项。例如上图所示的“华氏度“和“使用条款”放到反馈下面。并且去掉默认的标题。可以做到吗？

**Comment by hanbingwuxie** [comment]
这个插件没有办法修改顺序
