### ISSUE TITLE
您好，请问最新的开发文档在什么地方呢，感觉小米Iot平台的文档更新速度有点慢

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/NewXmPluginSDK#61]

**Comment by PioneerVM** [comment]
非常感谢您的回答,其实我想表达的意思是这样的，1.在最新的lib源码中可以看到startAddRoom、startSetTimerListV2等一些新的方法，但是文档中没有找到相关的介绍
2比如.在文档有这么个接口
/**
 * ApiLevel:3 设置定时场景
 *
 * @param model
 * @param did
 * @param us_id
 * @param name
 * @param setting
 * @param authed
 * @param callback
 */
@Deprecated
public void editTimerScene(String model, String did, int us_id, String name,
                           JSONObject setting,
                           JSONArray authed, final Callback<JSONObject> callback);
但是setting中的参数又需要传递些什么值呢？

**Comment by hanbingwuxie** [comment]
你好 model是指设备的model did就是设备ID了us_id如果是编辑之前的场景需要传递之前的新的无需传递，name就是场景的名字 setting 就是具体设置 的参数了，这个接口主要是用来修改之前的场景的。定时建议使用 IXmPluginHostActivity中的  startSetTimerList（）这个是定时接口
