### ISSUE TITLE
通用设置页和使用帮助页顶部有多余的阴影区。

### ISSUE THREAD

**Issue by denifer** [MiEcosystem/NewXmPluginSDK#62]

**Comment by hanbingwuxie** [comment]
能详细描述下，或者截个图么

**Comment by denifer** [comment]
![1545014895 1](https://user-images.githubusercontent.com/5772086/50063888-4a799300-01e9-11e9-8f2b-eb37f60dc2b4.png)

**Comment by wongzy** [comment]
您好，这是当前的UI布局，之后可能会有改变，目前是阴影区是设计中本来就有的。如果没有其他疑问的话请关闭此issue。
