### ISSUE TITLE
高压锅在做黄焖鸡 做好以后提示居然显示在破壁机图标上了 但是下拉菜单看到是高压锅的提示

### ISSUE THREAD

**Issue by denifer** [MiEcosystem/NewXmPluginSDK#65]
高压锅在做黄焖鸡 做好以后提示居然显示在破壁机图标上了 但是下拉菜单看到是高压锅的提示
![_20181217105216](https://user-images.githubusercontent.com/5772086/50064020-ddb2c880-01e9-11e9-8bac-d1062e9f41cb.jpg)
![_20181217105229](https://user-images.githubusercontent.com/5772086/50064021-e0152280-01e9-11e9-94a4-b21f1b27d239.jpg)

**Comment by wongzy** [comment]
你好，请问是哪个版本的sdk？
