### ISSUE TITLE
如果你遇到了插件无法更新的问题，不妨进来看看

### ISSUE THREAD

**Issue by evansherry** [MiEcosystem/NewXmPluginSDK#66]
本人在开发米家插件过程中，发现在新下载的米家中无法更新插件，经过了一顿操作后。。。
最后发现是由于文件读写权限未打开，但是我的测试机红米6A “文件读写手机存储”开关是打开的，
最后对比了华为的手机权限，所以初步断定这是“假装权限打开”，然后关闭手机权限，再手动打开，这时候如果你以为这就完事了，这是不可能的！！！ 依旧不可以，然后想到了是不是要在应用内申请权限，肯定还有别的申请入口， bingo，终于点击了“有品”按钮后，弹出了文件读写的权限框，然后就可以安装插件了。

如果安装不了插件，可能的情况：
1. 权限是否打开？
2.是否使用新版本的app?  如果是就需要在github更新plug.gradle文件

建议，在使用过程中，想清除下载的插件缓存，通常是通过清除米家app的数据，这样导致又要重新登录。。。，可否新增一个清除插件的功能？

**Comment by zanetti4** [comment]
请问您是哪个公司的开发者？这是什么产品？另外，我们这边对于旧版插件的 api 不再进行维护了，请知悉。

**Comment by zanetti4** [comment]
由于已经从老插件迁移了，故关闭此 issue
