### ISSUE TITLE
调试版apk问题

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/NewXmPluginSDK#67]
您好，请问现在的下载链接是正式版的吧？不能运行插件？

**Comment by wongzy** [comment]
你好，我们提供的是debug 版本的下载链接，可以运行插件，请参考[链接](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-Android%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/01-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E6%95%B4%E4%BD%93%E7%AE%80%E4%BB%8B)开发插件

**Comment by PioneerVM** [comment]
您好，之前的下载链接安装成功后，设置中显示的是XXX测试版，且运行插件后会提示安装插件成功，现在的版本没有 测试版字样，安装插件命令运行后也没有相关提示，且需要重新下载插件，还麻烦您，再确认下呗，谢谢

**Comment by wongzy** [comment]
> 您好，之前的下载链接安装成功后，设置中显示的是XXX测试版，且运行插件后会提示安装插件成功，现在的版本没有 测试版字样，安装插件命令运行后也没有相关提示，且需要重新下载插件，还麻烦您，再确认下呗，谢谢

您好，现在下载链接已更新，请重新下载调试版本apk，之前链接出错，抱歉。

**Comment by PioneerVM** [comment]
好的 谢谢

**Comment by hanbingwuxie** [comment]
你好如果问题解决请关下issue谢谢~
