### ISSUE TITLE
与[MJFAppConfigOperation shared] getAppconfigWithConfigName 有同样功能的接口是哪个？

### ISSUE THREAD

**Issue by bingerZhang** [MiEcosystem/NewXmPluginSDK#68]
[MJFAppConfigOperation shared] getAppconfigWithConfigName 是在IOS SDK中提供的接口，请问在andorid SDK中哪一个接口与之对应，有同样的功能？

**Comment by wongzy** [comment]
> [MJFAppConfigOperation shared] getAppconfigWithConfigName 是在IOS SDK中提供的接口，请问在andorid SDK中哪一个接口与之对应，有同样的功能？

您好，能否详细说明下iOS SDK中这个函数的参数及作用，Android中请求App config可使用XmPluginHostApi.instance().getAppConfig(String name, String lang, String version, Callback<String> callback)来获取

**Comment by bingerZhang** [comment]
感谢您的回复，问题已解决
