### ISSUE TITLE
请问，/device/setsetting的存储容量是多少？

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/NewXmPluginSDK#69]
你好：

请问，/device/setsetting的总存储容量是多少？单个Key值的存储容量是多少？
是否适用于保存操作记录类信息？

谢谢

**Comment by wongzy** [comment]
> 你好：
> 
> 请问，/device/setsetting的总存储容量是多少？单个Key值的存储容量是多少？
> 是否适用于保存操作记录类信息？
> 
> 谢谢

请问您说的问题在代码中怎么体现呢？我们Setting是使用的SharedPreferences进行存储的，并没有具体容量的限制，但是如果存储了大量数据的话会严重拖慢SharedPreferences的读取速度。

**Comment by wongzy** [comment]
> > > 你好：
> > > 请问，/device/setsetting的总存储容量是多少？单个Key值的存储容量是多少？
> > > 是否适用于保存操作记录类信息？
> > > 谢谢
> > 
> > 
> > 请问您说的问题在代码中怎么体现呢？我们Setting是使用的SharedPreferences进行存储的，并没有具体容量的限制，但是如果存储了大量数据的话会严重拖慢SharedPreferences的读取速度。
> 
> 下面是测试数据：
> 保存时，数据为：
> {"settings":{"Open_History":"{result=[{UserID=100000000, OperactionType=1, Data=1, Datetime=1546420429845, Name="D_Name"}, {UserID=100000000, OperactionType=1, Data=1, Datetime=1546420430616, Name="D_Name"}, {UserID=100000000, OperactionType=1, Data=1, Datetime=1546420431305, Name="D_Name"}]}"},"did":"1010266977"}
> 注：数据集有多条数据，我们测试了20条，为了节省篇幅，在上面的测试数据中只展示了数条。
> 
> 获取时，数据为：
> {"Open_History":"{result=[{UserID=100000000, OperactionType=1, Data=1, Datetime=1546419939685, Name="D_Name"}, {UserID=100000000, OperactionType=1, Data=1, Datetime=1546419940275, Name="D_Name"}, {UserID=100000000, OperactionType=1, Data=1, Da"}
> 
> 数据被截断了。

您好，能否贴一下具体的代码呢？

**Comment by oladevelope** [comment]
iOS代码：

  _setUserConfig(f_Id) {
    if (data == null) {
      MHPluginSDK.showFinishTips('添加失败');
      return;
    }
    if (data.length > 9) {
      data.splice(0, 1);
    }
    var resultObj = {};
    var jsonObject = {};
    jsonObject['F_ID'] = f_Id;
    jsonObject['F_Name'] = 'F_' + f_Id;
    jsonObject['RecordUserID'] = MHPluginSDK.userId;
    jsonObject['RecordDatetime'] = DateUtils.currentSecond;
    jsonObject['ModifyUserID'] = MHPluginSDK.userId;
    jsonObject['ModifyDatetime'] = DateUtils.currentSecond;
    data.push(jsonObject);
    resultObj['result'] = data;
    console.log(JSON.stringify(data));
    MHPluginSDK.callSmartHomeAPI('/device/setsetting',
      {
        'did': MHPluginSDK.deviceId,
        'settings': {
          'F_Data': JSON.stringify(resultObj)
        }
      }, (response) => {
        if (response != null && response.message != null && response.message.startsWith('ok')) {
          DeviceEventEmitter.emit('refreshFingerList', true);
          this._openSetName(f_Id);
          // this.props.navigator.pop();
        } else {
          MHPluginSDK.showFinishTips('添加失败');
        }
      });
  }

**Comment by oladevelope** [comment]
Andro代码：

    //设置数据
    public static String SETTINGDATA = "/device/setsetting";
    //获取数据
    public static String GETSETTINGDATA = "/device/getsetting";

		/**
     * 保存记录
     */

    public void saveDoorOpenHis() {

        Map<String, Object> map = new HashMap<>();
        Map<String, Object> mapx = new HashMap<>();
        Map<String, Object> mapxx = new HashMap<>();
        HashMap<String, Object> mapxxx = new HashMap<>();
        map.put("did", mDevice.getDid());
        map.put("settings", mapx);
        mapxxx.put("result", newList);
        mapxx.put("OperactionType", 1);
        mapxx.put("Datetime", String.valueOf(System.currentTimeMillis()));
        mapxx.put("UserID", XmPluginHostApi.instance().getAccountId());
        mapxx.put("Data", "1");
        newList.add(mapxx);
        mapx.put("O_History", mapxxx.toString());
        XmlUtils.setManagerData(mDevice, Params.SETTINGDATA, new JSONObject(map), map, 2);
    }


 		/**
     * 获取数据
     */
    public void getCloudData() {
        HashMap<String, Object> map = new HashMap<>();
        ArrayList<Object> list = new ArrayList<>();
        map.put("did", mDevice.getDid());
        map.put("settings", list);
        list.add("O_History");
        XmlUtils.setManagerData(mDevice, Params.GETSETTINGDATA, new JSONObject(map), map, 2);
    }




/**
     * 管理云存储数据
     * @param mDevice
     * @param url
     * @param jsonObject
     * s 1 存储 2 获取
     */
    public static void setManagerData(Device mDevice, String url, final JSONObject jsonObject, final Map<String,Object> map, final int s) {
        final DataReponse testBean = new DataReponse();
        Parser<JSONObject> parser = new Parser<JSONObject>() {
            @Override
            public JSONObject parse(String response) throws JSONException {
                // 注意：parse可能调用多次，在parse里面只能做解析数据操作，不能处理具体的业务逻辑
                // 具体业务逻辑，需要放到callback中收到回调后再进行处理
                JSONObject jsonObject1 = new JSONObject(map);

                testBean.setReponse(response);
                LogUtils.i("返回数据 -- "+"  result -- " +response);

                return jsonObject1;
            }
        };

        XmPluginHostApi.instance().callSmartHomeApi(mDevice.getModel(), url, jsonObject, new Callback<JSONObject>() {
            @Override
            public void onSuccess(JSONObject result) {
                LogUtils.i("存储设置数据 -- " +result +" parser result " + testBean.getReponse());
                if (s == 2){
                    if (mRequestCloudCallBack != null) {
                        mRequestCloudCallBack.onCloudCall(testBean.getReponse());
                    }
                }
            }

            @Override
            public void onFailure(int error, String errorInfo) {

            }
        }, parser);
    }

**Comment by aiquestion** [comment]
@oladevelope  请不要用户存储操作日志。存储key限制200个，value长度1024。这个目的是存储设备的设置，一般认为value很小，不适合存储大量数据。

**Comment by oladevelope** [comment]
> @oladevelope 请不要用户存储操作日志。存储key限制200个，value长度1024。这个目的是存储设备的设置，一般认为value很小，不适合存储大量数据。

好的，谢谢。
存储操作日志类的数据，可以使用那些接口？

**Comment by aiquestion** [comment]
具体什么需求呢？这个日志什么情况下会查看呢？

**Comment by oladevelope** [comment]
> 具体什么需求呢？这个日志什么情况下会查看呢？

想保存设备操作日志。可以使设备管理者方便的查看所有用户对设备的操作情况。
因为操作日志是和设备有直接关系的，操作者属于额外信息，所以没有考虑使用setUserConfig之类的接口。
而且在设备解除绑定的时候，这个接口保存的数据会被自动清除掉，数据的同步清除比较方便。

**Comment by aiquestion** [comment]
> > 具体什么需求呢？这个日志什么情况下会查看呢？
> 
> 想保存设备操作日志。可以使设备管理者方便的查看所有用户对设备的操作情况。
> 因为操作日志是和设备有直接关系的，操作者属于额外信息，所以没有考虑使用setUserConfig之类的接口。
> 而且在设备解除绑定的时候，这个接口保存的数据会被自动清除掉，数据的同步清除比较方便。

哦哦，可以当事件存储半年，麻烦先和对应的产品经理邮件沟通下需求，然后我们邮件里回复你接口文档吧。

**Comment by oladevelope** [comment]
> > > 具体什么需求呢？这个日志什么情况下会查看呢？
> > 
> > 
> > 想保存设备操作日志。可以使设备管理者方便的查看所有用户对设备的操作情况。
> > 因为操作日志是和设备有直接关系的，操作者属于额外信息，所以没有考虑使用setUserConfig之类的接口。
> > 而且在设备解除绑定的时候，这个接口保存的数据会被自动清除掉，数据的同步清除比较方便。
> 
> 哦哦，可以当事件存储半年，麻烦先和对应的产品经理邮件沟通下需求，然后我们邮件里回复你接口文档吧。

好的，谢谢
