### ISSUE TITLE
OTA接口获取数据为空

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/NewXmPluginSDK#70]
你好：

我在IOT开发平台-产品管理-固件管理中，上传固件升级文件，并获取签名。
然后使用XmPluginHostApi.instance().getBluetoothFirmwareUpdateInfo接口，去获取最新蓝牙固件信息时，获取到的数据为null。

我如何才能获取固件信息？

**Comment by wongzy** [comment]
请问确认参数中的model是非空且正确的吗？
![微信图片_20190107161817.png](https://i.loli.net/2019/01/07/5c330b556d4d8.png)

**Comment by oladevelope** [comment]
> 请问确认参数中的model是非空且正确的吗？
> ![微信图片_20190107161817.png](https://camo.githubusercontent.com/14b3e842c994b0fc3c91dc6b270426cbe99ae988/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f30372f356333333062353536643464382e706e67)

![image](https://user-images.githubusercontent.com/37095387/50759205-477d3a00-129f-11e9-9b6e-f793eddc834a.png)
使用getDevice，获得mDevice，然后model参数为mDevice.getModel

**Comment by hanbingwuxie** [comment]
上传的是否是白名单？获取的时候是否也是白名单

**Comment by wongzy** [comment]
你好，能debug然后给出具体的信息吗？这样可以让后台的同学帮忙排查一下，比如说device的did等信息

**Comment by oladevelope** [comment]
> 上传的是否是白名单？获取的时候是否也是白名单

是因为还没有把固件设置为白名单测试状态。
设置为白名单测试状态，就可以正确获取到固件信息了。
抱歉
