### ISSUE TITLE
iOS调用开锁命令报错

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/NewXmPluginSDK#72]
调用MHXiaomiBLE.toggleLockXiaoMiBLE接口，进行开锁操作时，报错，错误信息为timeout。
尝试更换timeoutInterval 的值，分别测试0.0, 2.0,10.0，都报timeout错。但是硬件已经执行了对应的动作。

下面是iOS上的代码
`MHXiaomiBLE.getDefaultDevice((error, device) => {
      if (error) {
        MHPluginSDK.showFailTips('连接失败');
            this.setState({
              show: false
            })
      } else {
        console.log(JSON.stringify(device));

        MHXiaomiBLE.loginXiaoMiBLE(MHPluginSDK.deviceId, device.mac, 10, (error, info) => {
          if (error) {
            MHPluginSDK.showFailTips('连接失败');
            this.setState({
              show: false
            })
          } else {
           // MHPluginSDK.showFailTips('连接成功');
            this.setState({
              show: true
            })
          }
        });
      }
    });`

`MHXiaomiBLE.toggleLockXiaoMiBLE(0, 2.0, (error, message) => {
      if (error) {
        //出错
        alert('error' + error.message);
        return;
      }
      this._getOpenRecord();
      // alert(JSON.stringify(message));
    });  `

**Comment by wongzy** [comment]
您好，iOS的问题请移步[链接](https://github.com/MiEcosystem/ios-rn-sdk/issues)
