### ISSUE TITLE
米家app新插件系统问题咨询

### ISSUE THREAD

**Issue by johnnykays** [MiEcosystem/NewXmPluginSDK#73]
请教一下， 米家app新插件系统中，智能插排，开启节能模式用的是哪个API？

**Comment by wongzy** [comment]
您好，插件是由第三方自主开发的，我们没有在公版插件中提供节能模式的API，不了解相关的信息。

**Comment by hanbingwuxie** [comment]
这个需要和设备交互 给设备发送数据有两种1 RPC消息XmPluginHostApi  callMethod /callMethodFromCloud
2. Spec协议的设备请使用DeviceController
