### ISSUE TITLE
关于 bluetooth.setAutoReconnect 的回调

### ISSUE THREAD

**Issue by dubiao** [MiEcosystem/NewXmPluginSDK#77]
调用 `XmBluetoothManager.getInstance().connect`  后，调用了
`XmBluetoothManager.getInstance().setAutoReconnect(address, true);` 
希望可以在断开后自动重连，但是连接上后，并没有自动执行 原来connect的回调。
请问自动重连后，如何可以执行回调 ？

**Comment by wangchongwhut** [comment]
这个接口现在废弃了，不支持设备断开重连
