### ISSUE TITLE
固件更新

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#78]
你好，我在做固件更新中。从菜单项进入到通用设置页面（检查固件更新菜单项）默认获取到有更新状态，红点显示。再进入到更新界面。我点击立即升级，然后升级完成。到成功页面。之后点击成功页面的确定按钮，此时当前成功页面销毁。然后通用设置页面出现。这个时候我需要更新通用设置页面的红点状态。

![2ba5298db169008c2b318228d5c859e](https://user-images.githubusercontent.com/29192190/51578753-91019200-1ef9-11e9-9ad9-40c39020f5d5.jpg)
![0466ad6c5b124bd264cf34cb275ad03](https://user-images.githubusercontent.com/29192190/51578773-ab3b7000-1ef9-11e9-953a-6330283d40db.jpg)
![955928cb770329f3457ca1c078e4071](https://user-images.githubusercontent.com/29192190/51578779-b098ba80-1ef9-11e9-9c49-3bc41ac5c25a.jpg)

**Comment by hanbingwuxie** [comment]
不太明白你要干啥？能整理下步骤和期望的结果么

**Comment by zanetti4** [comment]
@hanbingwuxie 他的意思大概是：升级成功后回到通用设置页面，检查固件更新的红点依然存在。他想让红点消失。

**Comment by zanetti4** [comment]
@Tywei24  这个问题现在解决了吗？
