### ISSUE TITLE
BLE固件更新问题

### ISSUE THREAD

**Issue by xfengltl** [MiEcosystem/NewXmPluginSDK#79]
BLE --OTA升级部分遇到点问题，需要协助一下。

    目前情况：
    设备固件版本：2.1.5_0001
   米家后台固件：2.1.5_0002（已发布） 设置成白名单测试
   开发者账号：已加入测试白名单
   手机APP能获得到设备的版本号和米家后台已上传固件版本号。 现在升级到99%一直卡住，设备端也没有新的提示。

**Comment by wongzy** [comment]
你好，能提供下log信息吗？

**Comment by xfengltl** [comment]
> app不负责升级，在BleUpgrader startUpgrade()时候 需要插件调用XmPluginHostApi.instance().downloadBleFirmware（）下载固件，下载完成后需要传递给设备 调用 XmBluetoothManager wite()函数写入设备 完成固件升级！

不能使用原厂的DFU吗？

**Comment by zanetti4** [comment]
该问题是否已经解决了？
