### ISSUE TITLE
米家卡片在Android上的配置

### ISSUE THREAD

**Issue by EllisonYe** [MiEcosystem/NewXmPluginSDK#85]
按照米家提供的配置说明（[配置说明](https://iot.mi.com/new/guide.html?file=05-%E7%B1%B3%E5%AE%B6%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/02-Android%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/20-%E7%B1%B3%E5%AE%B6%E5%8D%A1%E7%89%87%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)），有以下几点需要确认：
1、将json文件中的文本拷贝放入mijia_card_config.txt文件(必须保存为UTF-8编码格式，否则卡片会显示乱码)，拷贝至手机根目录即可调试。（问题：是放到手机根目录还是插件的根目录？另外手机根目录是需要权限的）
2、cardType，每个具体对应的配置说明以及demo

**Comment by zanetti4** [comment]
涉及到的设备是什么？
