### ISSUE TITLE
撤销“使用条款和隐私协议” 如何能退出插件？

### ISSUE THREAD

**Issue by badsdy** [MiEcosystem/NewXmPluginSDK#86]
通用设置里撤销“使用条款和隐私协议”，如何能退出插件呢？有回调信息给插件吗？

**Comment by lvjie0519** [comment]
1、弹出 确认撤销授权  dialog的时候点击 确认 ，不会自动退出插件吗？
2、尝试在onActivityResult函数通过intent获取返回值
