### ISSUE TITLE
通用设置-定时开关功能异常

### ISSUE THREAD

**Issue by DennisJu007** [MiEcosystem/NewXmPluginSDK#88]
1、调用的API
  /**
     * ApiLevel: 8 startSetTimerList(mDeviceStat.did, "set_rgb",
     * String.valueOf(0x00ffffff), "set_rgb", String.valueOf(0x00000000),
     * mDeviceStat.did, "RGB灯定时器", "RGB灯定时器");
     *
     * @param deviceId    device id
     * @param onMethod    当on timer时间到的时候执行的action，执行原始数据
     * @param onParams    on action的参数
     * @param offMethod   当off timer时间到的时候执行的action，执行原始数据
     * @param offParams   off action参数
     * @param identify    定时器的identify，使用device id
     * @param displayName 定时的名称,在场景执行日志中显示
     * @param timerTitle  定时器标题
     */
    public void startSetTimerList(String deviceId, String onMethod, String onParams,
                                  String offMethod, String offParams, String identify, String displayName,
                                  String timerTitle);
2、uid：268240019
3、操作步骤：进入mono1的设备设置界面-定时开关-定时开关列表页面，如果之前设置过定时任务，此时发现不能删除也不能操作。

**Comment by DennisJu007** [comment]
1、调用的API
  /**
     * ApiLevel: 8 startSetTimerList(mDeviceStat.did, "set_rgb",
     * String.valueOf(0x00ffffff), "set_rgb", String.valueOf(0x00000000),
     * mDeviceStat.did, "RGB灯定时器", "RGB灯定时器");
     *
     * @param deviceId    device id
     * @param onMethod    当on timer时间到的时候执行的action，执行原始数据
     * @param onParams    on action的参数
     * @param offMethod   当off timer时间到的时候执行的action，执行原始数据
     * @param offParams   off action参数
     * @param identify    定时器的identify，使用device id
     * @param displayName 定时的名称,在场景执行日志中显示
     * @param timerTitle  定时器标题
     */
    public void startSetTimerList(String deviceId, String onMethod, String onParams,
                                  String offMethod, String offParams, String identify, String displayName,
                                  String timerTitle);
2、uid：268240019
3、操作步骤：进入mono1的设备设置界面-定时开关-定时开关列表页面，如果之前设置过定时任务，此时发现不能删除也不能操作。
4、
![101553826360_ pic_hd](https://user-images.githubusercontent.com/42829167/55369785-964b1080-552a-11e9-8fb5-424224a8b719.jpg)

**Comment by zanetti4** [comment]
请问涉及到的设备是什么？该问题出现在什么手机系统？
