### ISSUE TITLE
插件上传后，提示错误

### ISSUE THREAD

**Issue by oladevelope** [MiEcosystem/NewXmPluginSDK#91]
![image](https://user-images.githubusercontent.com/37095387/56259840-24b4ba00-6107-11e9-8a70-420dc991d1e8.png)

如图
之前的上传都没有问题，昨天更新代码后，进行上传，上传结束后，提示这个错误

**Comment by qfeelrelease** [comment]
我也遇到了, 不过第二天就没问题了

**Comment by zanetti4** [comment]
现在该问题还存在吗？

**Comment by oladevelope** [comment]
问题不存在了，第二天就恢复正常了。
