### ISSUE TITLE
Android 9.0 新版本debug米家无法安装插件的问题

### ISSUE THREAD

**Issue by PioneerVM** [MiEcosystem/NewXmPluginSDK#93]
我们用的红米6 ，米家5.4.54测试版，系统是Android 9 ，也更新了下sdk中最新的 plug.gradle，但是仍然不能安装插件，不提示插件安装成功，点击进入插件也不是需要安装的插件，请问是什么原因呢

**Comment by dingshaoran** [comment]
请使用如下命令尝试
adb push 你的插件   /sdcard/SmartHome/plugin/debug/9.mpk
adb shell  am force-stop com.xiaomi.smarthome
adb shell  am start com.xiaomi.smarthome/.SmartHomeMainActivity
adb shell am broadcast -a com.xiaomi.smarthome.action.OPEN_API -n com.xiaomi.smarthome/.framework.openapi.OpenApiReceiver --es type plugin_debug --es sub_type debug_package
