### ISSUE TITLE
关于华为手机偶尔订阅失败,但小米手机能订阅成功

### ISSUE THREAD

**Issue by qfeelrelease** [MiEcosystem/NewXmPluginSDK#94]
我们这边测试的时候,偶尔出现全体华为手机订阅失败的现象, 但小米手机正常使用, 然后过一段时候会恢复正常, 订阅失败的错误码-8,提示invalid param, 请问这是什么错误?

**Comment by zanetti4** [comment]
请问涉及到的是什么设备？
