### ISSUE TITLE
米家插件 通用设置 为什么没有 修改设备名称和删除设备接口？

### ISSUE THREAD

**Issue by Aphrodite123** [MiEcosystem/NewXmPluginSDK#95]
想在通用设置中自定义 修改设备名称和删除设备，但是未找到相对应的接口

**Comment by LiuMengzhou** [comment]
啥意思？
你想屏蔽还是还是自定义样式？
目前根据产品需要这两项必选，且UI不可更改

**Comment by Aphrodite123** [comment]
我是想自定义 修改设备名称和删除设备 两个设置，但是在点击这两个按钮的时候分别调用插件里面默认的样式和处理逻辑

**Comment by Aphrodite123** [comment]
历史原因：老版插件，Android和iOS 通用设置展示的功能不一样，所以想着在第一级页面自己定义，然后在点击后下一级直接调用插件接口

**Comment by zanetti4** [comment]
请问您是哪个公司的开发者？这是什么产品？另外，我们这边对于旧版插件的 api 不再进行维护了，请知悉。
