### ISSUE TITLE
【新品】+【无项目ID】+【洒哇地咔】+【MT】

### ISSUE THREAD

**Issue by qfeelrelease** [MiEcosystem/NewXmPluginSDK#96]
【新品】+【无项目ID】+【洒哇地咔】+【MT】
我们的安卓app调试过程中发现BaseDevice.callMethod函数偶尔会出现(-104): no did的错误, 出现的概率大概是10几次出现一次, 请问什么情况下可能导致这个问题? 因为配网是能配成功的, 所以我们这边认为应该不是设备端did格式有问题, 因为did错误的话首先配网不会成功. 另外我们这边可能存在网络延迟的问题, 因此会不会由于请求超时而出现no did的错误?

**Comment by dingshaoran** [comment]
logcat 过滤 MIIO ,把你对应个请求log 发一下
例如：
05-20 12:25:59.479 18232-18499 D/MIIO: host:api.io.mi.com prefix:nullpath:/home/rpc/257326535 method:POST params:[data:{"id":8460,"method":"alarm_ops","params":{"operation":"query","req_type":"alarm","index":0}}]
05-20 12:25:59.479 18232-18499 D/MIIO: {"code":0,"id":8460,"result":[0,[],"Asia/Shanghai"]}

**Comment by qfeelrelease** [comment]
这个问题最近没出现过, 不太好复现, 等出现的时候我再反馈. 
还有另一个问题请教一下, 安卓端XmPluginHostApi.instance().setPropertyValue应该就是设置属性的函数吧, 里面这个PropertyParam我没太看懂怎么用, siid和piid分别代表什么意思?例如我想设置一个water的属性, 但是里面没发现有设置water这个字符串的地方, 例子中也没找到相应的介绍.

**Comment by zanetti4** [comment]
如果涉及到不同的问题，请再新建一个 issue 吧。
