### ISSUE TITLE
旧版米家app绑定新开发插件问题

### ISSUE THREAD

**Issue by Tywei24** [MiEcosystem/NewXmPluginSDK#97]
你好，我现在使用旧版米家app5.1.39，然后添加我们自己的插件。添加之后打开crash。
插件配置版本：
compileSdkVersion 27
    buildToolsVersion '26.0.2'

    defaultConfig {
        //需要配置为插件包名
        applicationId "com.miaomiaoce.sensor_ht"
        minSdkVersion 19
        targetSdkVersion 26
        //每次发布版本versionCode必须加1
        versionCode 79
        versionName "1.0.78"
    }

        <meta-data android:name="minPluginSdkApiVersion" android:value="76" />

**Comment by Tywei24** [comment]
补充：我目前所使用的版本，是以上的版本。但是在用5.1.39的米家app拉取现在的插件，拉取不到。绑定的还是之前的老版本插件。

**Comment by Tywei24** [comment]
总结：我们遇到一个问题，我们的插件使用了比较新的接口，但是之前的插件里填写的minPluginSdkApiVersion版本特别低。导致部分用户使用旧的米家APP打开我们的插件会crash。我们在新的插件更正了这个问题，但是我们发现如果用户的米家APP版本是5.1.39及以下，则用户没法升级到我们新的插件。米家对此没有提示，所以用户会一直crash。想问一下这种情况是正常的吗？有什么好的处理方法吗？

**Comment by lvjie0519** [comment]
1、在使用新接口的时候，建议做一个apiLevel的判断；
2、将你的minPluginSdkApiVersion修改为和以前一致，APP下载插件是通过minPluginSdkApiVersion判断的。

**Comment by Tywei24** [comment]
我之前minPluginSdkApiVersion是2，看米家开发文档上如下接口是76，然后我就把minPluginSdkApiVersion改为76了。现在要恢复之前2的话，那么是否超过2的接口都要进行判断呢，我该如何判断呢，能给个例子吗？
/**
 * Apilevel:76
 *
 * @param dialogTitle
 * @param licenseTitle
 * @param licenseHtml   用户协议Html内容
 * @param privacyTitle
 * @param privacyHtml   隐私条款Html内容
 * @param agreeListener
 */
void showUserLicenseHtmlDialog(String dialogTitle,
                                   String licenseTitle, String licenseHtml,
                                   String privacyTitle, String privacyHtml,
                                   View.OnClickListener agreeListener);

**Comment by lvjie0519** [comment]
理论上是需要进行判断，通过XmPluginHostApi.instance().getApiLevel(）可以获取当前apk支持的版本。
